### ISSUE TITLE
Grondwaterstand bij GAR

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#1]
Tijdens veldonderzoek naar grondwaterkwaliteit, wordt ook de grondwaterstand gemeten. We denken dat het relevant is om dit gegeven ook op te nemen in het GAR veldonderzoekresultaat hoewel het GAR eigenlijk gaat over grondwaterkwaliteit en niet de kwantiteit (de stand).

Argument om het gegeven nu wel op te nemen is de hergebruikswaarde voor beoordeling/synthese:
- Hoever bevindt bv het (bemonsterde) grondwater zich onder maaiveld
- Analyse in ruimte: wat is het regionale stromingspatroon van het freatisch grondwater

Een open vraag is nog hoe de grondwaterstand tijdens het veldwerk van grondwatersamenstellingsonderzoek wordt gemeten en hoe het resultaat wordt vastgelegd. Voor zover wij konden achterhalen wordt de grondwaterstand doorgaans bij veldonderzoek gemeten door een meetlint in de buis te steken en de stand te meten in aantal centimeters ten opzichte van bovenkant buis. Klopt dat? En wordt dit genoteerd in hele cm's of met cijfers achter de komma i.e. wat is het bereik?

**Comment by lvdbrink** [comment]
Opmerking hierbij: de aanduiding van grondwaterstand in centimeters t.o.v. bovenkant buis is wellicht niet handig als BRO inhoud. Alternatief: t.o.v. maaiveld of NAP.

**Comment by lvdbrink** [comment]
Dit is bij enkele mensen uit de praktijk nagevraagd. De grondwaterstand wordt tijdens een bemonstering inderdaad met meetlint gemeten en gerapporteerd in diepte tov bovenkant buis. 

De stand wordt gerapporteerd in meters met twee cijfers achter de komma – bijvoorbeeld 2,52 m.

In de BRO is de positie bovenkant buis van een put bekend ten opzichte van NAP. De grondwaterstand ten opzichte bovenkant buis kan dus worden omgerekend naar de stand ten opzichte van NAP.

**Comment by lvdbrink** [comment]
De relevantie van `grondwaterstand` als één van de veldmetingen die wordt opgenomen in de BRO staat toch nog ter discussie. Argumenten voor/tegen zijn (voor zover tot nu toe gehoord): 

Argumenten **tegen** opname grondwaterstand bij grondwatersamenstellingsonderzoek: 
- Het meten van de grondwaterstand is ondersteunend voor het proces monstername, om te weten hoeveel water je leeg moet pompen, maar je zou te veel waarde eraan toekennen als je het op zou nemen in de BRO. 
- De grondwaterstand opnemen bij grondwatersamenstellingsonderzoek is verwarrend want dit zit in een ander BRO registratieobject: Grondwaterkwantiteit. Je zou hiermee grondwaterstanden krijgen in 2 registratieobjecten met een verschillende grondslag. 

Argumenten **voor** opname grondwaterstand bij grondwatersamenstellingsonderzoek: 
- De hergebruikswaarde voor beoordeling/synthese, nl hoever bevindt het (bemonsterde) grondwater zich onder maaiveld; en analyse in ruimte: wat is het regionale stromingspatroon van het freatisch grondwater.

**Comment by AnnitaVijverberg** [comment]
Indien de grondwaterstand relevant is voor het resultaat en beoordeling van grondwaterkwaliteit dan moet het worden opgenomen. Wat is precies de relevantie?

**Comment by AnnitaVijverberg** [comment]
Conclusie na diverse gesprekken met experts: De grondwaterstand is een belangrijke parameter om op te nemen. Voor de interpretatie van meetwaarden is het belangrijk inzicht te hebben in de grondwaterstand op het moment van monstername.

**Comment by AnnitaVijverberg** [comment]
Bovendien wordt de grondwaterstand veelal niet in dezelfde putten gemeten als de grondwatersamenstelling

**Comment by AnnitaVijverberg** [comment]
Op verschillende momenten moet volgens de NTA de grondwaterstand gemeten worden maar welke is het meest relevant op vast te leggen? Na gesprek met Erik: wat relevant is voor hergebruik, is de filterdiepte, daar komt het bemonsterde grondwater vandaag. Een gebruiker wil weten van welke diepte het bemonsterde grondwater komt. De filterdiepte is te achterhalen in GMW. Alle grondwaterstanden die gemeten worden dienen het proces van monstername: instellen van het juiste debiet, zorgen dat het filter niet droogvalt en de gw-stand niet teveel daalt. Dit is allemaal ondervangen door de procedure en de bijzonderheden. De grondwaterstand heb ik daarom verwijderd uit het model.
