### ISSUE TITLE
Regels rond opname bicarbonaat veldmeting in de BRO

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#10]
Op dit moment maakt het GAR informatiemodel het mogelijk, maar niet verplicht, om een veldmeting voor bicarbonaat te noteren en in de BRO op te nemen. Is dit juist, of zou dit moeten zijn: 
- bicarbonaat verplicht opnemen.
- bicarbonaat helemaal niet opnemen (ook niet optioneel).

Voor zover wij kunnen nagaan wordt bicarbonaat niet standaard in het veld gemeten. Bijvoorbeeld de Omgevingsdienst Westbrabant (OMWB) doet deze meting niet (meer), met als reden dat er vaak grote, onverklaarbare verschillen tussen de veld en lab waarde waren. Het meten van bicarbonaat vergt titratie in het veld. 

Bronnen (tot nu toe gevonden) die hier iets over zeggen: 
- In de NTA8017 is niet vastgelegd dat bicarbonaat moet worden gemeten. Wel staat daarin dat dit "vaak" wel gemeten wordt. 
- In het Draaiboek monitoring grondwater KRW (2013) staat dat waterstofcarbonaat aka bicarbonaat (HCO3-) in lab + veld gemeten wordt, in "Tabel 5.3: minimum analysepakket voor de surveillance monitoring en eisen aan de detectielimieten" (p. 40).
- In Deel 1: Handboek Monitoring Grondwaterkwaliteit KRW provincies en RIVM
Versie: PMB_update2016_06042017: "Meet indien nodig in het gefiltreerde monster direct na monsterneming de HCO3-concentratie conform het werkvoorschrift." (p. 64)

Aanvullende informatie en discussie hierover zijn welkom.

**Comment by lvdbrink** [comment]
Marielle van Vliet (TNO): 
> Deze wordt vaak wel gemeten in het veld: of met een veld-titrator (bijv.hand held set) of met een lab titrator die is ingebouwd in de veldbus. Indien gemeten dan moet deze ook echt opgeslagen kunnen worden. Maar geen verplicht veld. Er kan iets in het veld gebeuren, waardoor deze meting een keer ontbreekt. Indien bicarbonaat niet in het veld wordt gemeten, zal deze wel in het lab worden bepaald.

**Comment by lvdbrink** [comment]
NB: bicarbonaat is een verouderde term? https://nl.wikipedia.org/wiki/Waterstofcarbonaat

**Comment by AnnitaVijverberg** [comment]
- Bicarbonaat wordt vaak gemeten. Wanneer bicarbonaat niet gemeten in het veld? Wat is hiervan in die gevallen de reden? Het vergt titratie in het veld. Is hier specifieke kennis of apparatuur voor nodig?
- Welke informatie is belangrijk uit deze meting? Waar wordt het resultaat voor gebruikt?

**Comment by AnnitaVijverberg** [comment]
Conclusie na gesprekken met diverse experts: Het bicarbonaatgehalte is een belangrijk waarde om te meten omdat dit van invloed is op de ionenbalans. Het bicarbonaatgehalte verandert door invloeden van buitenaf. Het is daarom belangrijk het bicarbonaat in het veld te meten. Het meten van bicarbonaat in het veld vergt kennis en nauwkeurigheid van de veldmedewerker maar is mits zorgvuldig uitgevoerd goed te doen.

**Comment by AnnitaVijverberg** [comment]
Tijdens de sprintreview gaven provincies aan: Metingen, met name die voor bicarbonaat, worden niet altijd uitgevoerd. Nu staat er een kardinaliteit van 1, het gegeven moet dus altijd aangeleverd worden. Dat kan niet als het niet gemeten wordt.

**Comment by AnnitaVijverberg** [comment]
In de praktijk van gegevensuitwisseling is het mogelijk een attribuut op te nemen zonder waarde. Voor attributen geldt dat de kardinaliteit en de regels samen bepalen of een attribuut al dan niet aanwezig is en of een attribuut al dan niet een waarde heeft. Uitgangspunt is dat een attribuut dat aanwezig is een waarde heeft. Een attribuut wordt alleen bij uitzondering zonder waarde in de berichten opgenomen. Het onderstaande overzicht geeft de vier mogelijkheden die voorkomen.
*  De kardinaliteit= [1] en er is geen aanvullende regel opgenomen. Dit betekent dat het gegeven altijd aanwezig is en altijd een waarde heeft.
*  De kardinaliteit= [1] en er is een aanvullende regel opgenomen die aangeeft waarom een waarde toch mag ontbreken. Dit betekent dat het gegeven altijd aanwezig is maar bij uitzondering en om een specifieke reden geen waarde kan hebben.
*  De kardinaliteit= [0..1] en er zijn 1 of meer aanvullende regels opgenomen. Dit betekent dat de regels bepalen of het gegeven wel of niet voorkomt en bepalen of het gegeven wel of geen waarde heeft.
*  De kardinaliteit= [0..1] en er is geen aanvullende regel opgenomen. Dit betekent dat het gegeven alleen aanwezig is als het een waarde heeft.

Bij de veldmeting van het bicarbonaat gehalte is de kardinaliteit 1 en er is een regel opgenomen: “Door uiteenlopende oorzaken kan het voorkomen dat het bicarbonaatgehalte niet bepaald is. Alleen in dat geval heeft het attribuut geen waarde.”
Bied dit voldoende ruimte in het geval bicarbonaat niet is bepaald in het veld?

**Comment by AnnitaVijverberg** [comment]
Hangt samen met meetnetten en kader inwinning: in welke meetnetten en voor welk doel wordt wel/niet opdracht gegeven voor meten van waterstofcarbonaat in het veld?

**Comment by JvVelthuijsen** [comment]
Het gehalte bicarbonaat kan een belangrijke waarde zijn om te meten. 
Het meten in het veld betekent ook dat er met chemicaliën moet worden gewerkt in het veld (titratie) en dat is geen gewenste situatie. Titreren in winterse omstandigheden is zeker niet aan te raden.

**Comment by AnnitaVijverberg** [comment]
Wij concluderen dat het waterstofcarbonaatgehalte belangrijk is om te meten maar dat het in de praktijk niet altijd gemeten wordt.  Ook is het tijdens de monsterneming geen verplichte parameter om te meten (zie ook #36).
Om die reden heeft dit attribuut kardinaliteit [0..1] gekregen

**Comment by AnnitaVijverberg** [comment]
We sluiten dit issue zoals besproken in de sprintreview van 25 okt 2018
