### ISSUE TITLE
'nietVolledig' in codelijst StatusKwaliteitscontrole sluit andere opties niet uit

### ISSUE THREAD

**Issue by TrefoilHydrology** [BROprogramma/GAR#112]
## Type issue
Publieke consultatie

## Waar
GAR catalogus paragraaf 1.2.7. Codelijst details StatusKwaliteitscontrole

## Samenvatting
'nietVolledig' in codelijst StatusKwaliteitscontrole sluit andere opties niet uit

## Beschrijving
Dat de voorgeschreven kwaliteitscontroles niet allemaal kunnen worden uitgevoerd, betekent niet dat de gegevens niet bijv. ook afgekeurd of goedgekeurd kunnen worden.  De eigenschap volledigheid is van een andere orde dan het eindoordeel, en sluit daarmee de andere opties niet uit.

## Oplossingsrichting
De optie nietVolledig verwijderen uit de Codelijst.

**Comment by AnnitaVijverberg** [comment]
Oordeel niet-volledig: in het geval van historische gegevens kunnen inderdaad gegevens niet-volledig EN goedgekeurd (of afgekeurd etc.) zijn. Dus je zou een apart veld niet-volledig j/n nodig hebben. Deze situatie geldt alleen voor IMBRO/A, dus te  zwaar om daar SIKB wijzigingen voor aan te vragen. We hebben besloten er geen apart veld voor te maken. Maar wel: 
•	De definitie goedgekeurd, onbeslist en afgekeurd aan te vullen met een toelichting dat het bij IMBRO/A gegevens zo kan zijn dat het is goedgekeurd (onbeslist/afgekeurd) aan de hand van een niet volledig gevolgde procedure. 
•	nietVolledig verwijderen uit de codelijst
