### ISSUE TITLE
ID's en GUIDs

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GAR#114]
Roeland Heuff, SIKB
## Type issue
Publieke consultatie

## Waar
BRO-ID, 1.1.1.1 blz 4

## Beschrijving
Om in de uitwisseling unieke ID’s te hebben wordt binnen Metingen door het hele model met GUID’s gewerkt. Dit werkt erg handig ook bij het ‘updaten’ van resultaten. Je weet op elk niveau of het een nieuw resultaat is of een reeds eerder opgevoerd resultaat. BRO lijkt heel anders om te gaan met ID’s. Het moeten opvragen van een BRO-ID om later resultaten te kunnen koppelen lijkt ons niet werkbaar.

**Comment by AnnitaVijverberg** [comment]
Roeland Heuff, SIKB
## Type issue
Publieke consultatie

## Beschrijving
In de codelijsten is niet duidelijk wat het sleutelveld is. Binnen SIKB0101/AQUO/Metingen zijn de ID’s het sleutelveld (geen Aquo codes!).

**Comment by AnnitaVijverberg** [comment]
Gebruik maken van GUID's ipv (of naast BRO-ID's is GAR overstijgend en is besproken met PO en bouw.

De parameterlijst hebben we aangepast, nu vormt het ID de sleutel. De parameterlijst is de enige referentielijst binnen GAR. De andere waardenlijsten zijn codelijsten waar het binnen de BRO niet gebruikelijk is te werken met ID's, die hebben we niet aangepast.

**Comment by RLHuisman** [comment]
Het idee van de ID's was niet voor de codelijsten maar ging juist om de Peilbuizen bijv. van een GUID te voorzien op de plek waar deze als eerste wordt geregistreerd. Zodat iedereen die deze peilbuis binnenkrijgt dit GUID kan laten behouden, iedereen in de keten heeft het dan over dezelfde peilbuis.
Als er dan watermonsters worden genomen door verschillende partijen, komen deze obv Peilbuis GUID bij de juiste Put terecht en hoeft niemand BRO-IDs te gaan zitten overtypen.
