### ISSUE TITLE
Eén GAR, één doel, één bronhouder?

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#12]
[Par 3.1][1], eerste alinea onder de genummerde lijst:

> Daarbij zijn uitgangspunten dat een grondwatersamenstellingsonderzoek één bronhouder en één doel heeft, ..

Signalen uit de praktijk geven aan dat een grondwatersamenstellingsonderzoek vaak met voorbedachten rade voor meerdere doelen genomen wordt. Bijvoorbeeld zowel voor het doel van PMG-Brabant als voor KRW-Zand-Maas. Zelfde bronhouder, zelfde onderzoek, meer doelen. Meerdere bronhouders schijnt ook voor te komen. 

In het huidige model is het echter niet mogelijk om meerdere doelen of meerdere bronhouders bij één grondwatersamenstellingsonderzoek (GAR) op te nemen. Dit heeft als consequentie dat het desbetreffende GAR niet onder het andere doel terug te vinden zal zijn in de BRO LV. Idem voor de situatie van meerdere bronhouders.

Echter, in een basisregistratie is het een grondbeginsel dat één object één bronhouder heeft. Dit principe is hier toegepast.

**NB** Andere argumenten voor het toestaan van slechts één bronhouder en één doel zijn nog niet in dit issue gedocumenteerd. 

[1]: https://broprogramma.github.io/GAR/#intro-GAR

**Comment by lvdbrink** [comment]
"...Het kunnen opnemen van meerdere doelen of meerdere bronhouders bij één grondwatersamenstellingsonderzoek (GAR) ..."

Marielle van Vliet (TNO): 
> Ja, dat is mijn inziens zeker gewenst.

**Comment by AnnitaVijverberg** [comment]
Kader inwinning en kader aanlevering zijn geen onderdeel meer van GAR. Het meetdoel en kader aanlevering zijn opgenomen in GMN (monitoringnet). Een GAR verwijst naar 1 of meer monitoringnetten. Daarmee kan een GAR dus gekoppeld zijn aan meer meetdoelen. Verder is een GAR gekoppeld aan een monitoringbuis in een meetput. Daarmee kan het voorkomen dat de bronhouder van een GAR een andere is dan de bronhouders van de meetput waarin is bemonsterd en een andere is dan de (een) bronhouder van het monitoringnet waaraan het GAR is gekoppeld.
