### ISSUE TITLE
Wel/niet vastleggen type grondwater

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#13]
Het [type grondwater][1] wordt in het huidige conceptmodel als attribuut bij het Grondwatersamenstellingsonderzoek vastgelegd. Definitie: 

> De aard van het grondwater, geclassificeerd op basis van chloridegehalte.

De vraag is of dit wel relevante informatie is om in het GAR op deze plek op te nemen. Het is een interpretatie van chloridemetingen. 

[1]: https://broprogramma.github.io/GAR/#detail_attribute_Model_Grondwatersamenstellingsonderzoek_typeGrondwater

**Comment by lvdbrink** [comment]
Nog een argument om het niet op te nemen is: het is een vast gegeven, niet iets dat wisselt in de loop der tijd. 

Dit gegeven zal waarschijnlijk uit het conceptmodel worden gehaald, tenzij er argumenten worden aangedragen om dit wél op te nemen.

**Comment by AnnitaVijverberg** [comment]
- Op welk moment in het proces is bekend (of moet bekend zijn) of het om zoet of zout water gaat? 
- Ec wordt gemeten; zoet/zout kan daar van worden afgeleid; is het dan nodig om type grondwater op te nemen?

**Comment by lvdbrink** [comment]
Conclusie na gesprekken met diverse experts: Het onderscheid tussen zoet en zout grondwater is binnen het onderzoek niet relevant, maar wel voor het proces van inname en voor gebruikers. 
Het waardebereik van bepaalde stoffen is in zoet grondwater (chloridegehalte minder dan 300 mg/l ) anders in dan in zout grondwater. Voor de controles bij de inname van gegevens is het onderscheid daarom een sturend gegeven. 
Voor gebruikers is het gegeven interessant omdat zij op basis van dat gegeven makkelijk een eerste keuze maken uit het geheel van gegevens dat de BRO aanbiedt.  
De informatiebehoefte van die twee partijen kan op twee manieren worden gedekt, door de waarde van het in het lab bepaalde chloridegehalte of door een extra gegeven op te nemen. Wat de beste keuze is nog niet vastgesteld. 

Vooralsnog laten we het gegeven weg. We kunnen het later altijd toevoegen als dat nodig is.
