### ISSUE TITLE
Layout: tekst afbreken

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GAR#134]
Mariëlle van Vliet, TNO:
## Type issue
Publieke consultatie

## Waar
Gehele tekst onder Toelichting

## Beschrijving
Deze tekst zou prettiger lezen als "automatisch afbreken" van lange woorden wordt ingesteld.

**Comment by lvdbrink** [comment]
In de juridische versie van de catalogus kunnen we dit in Word instellen. 

In de publieksvriendelijke versie van de catalogus is het afhankelijk van de gebruikte web browser. Firefox ondersteunt automatisch afbreken; in andere browsers is de ondersteuning wisselend. Uitzoekpunt: nagaan of ReSpec dit kan ondersteunen voor meer browsers.
