### ISSUE TITLE
Hoe modelleren van veldparameters

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#14]
In de klasse `Resultaat veldmetingen` staan de veldparameters opgenoemd waarvan we voorstellen om ze op te nemen in de BRO. Te weten: 
- `geleidbaarheid`
- `bicarbonaatgehalte`
- `zuurgraad`
- `temperatuur`
- `troebelheid`
- `grondwaterstand`
- `zuurstofgehalte`

Het is nog onzeker of de veldparameters op deze wijze zullen worden gemodelleerd. Dit is een modeltechnische kwestie; inhoudelijk is de voorgestelde lijst veldparameters bekend, maar de vraag is nog of ze als attributen van `Resultaat veldmetingen` worden gemodelleerd. Nadeel hiervan is
- het schaalt niet (in het andere deel van het GAR, het laboratoriumonderzoek, komen honderden parameters)
- als er in de loop der tijd meer parameters bij komen omdat het veldwerk evolueert, vereist dit een aanpassing van de standaard dmv toevoegen van attributen, wat een wijziging met vrij grote impact is. 

Alternatief (vergelijkbaar met huidige modellering van laboratoriumresultaat): 
- Opnemen van een generiek attribuut `Parameter` met: 
  - `naam` (codelijst met `geleidbaarheid`, `bicarbonaatgehalte`, enz)
  - `waarde `(de gemeten waarde)

Voordeel is dat een codelijst eenvoudig uit te breiden is indien nodig en dat dit lage impact heeft; en dat dan per parameter ook kan worden opgenomen of deze in- of ex situ gemeten is en of er relevante bijzonderheden waren bij de meting, bijvoorbeeld een afwijking in de meetapparatuur.  

Nadeel van deze modelleerwijze is vooral modeltechnisch: het is niet mogelijk om in het informatiemodel per parameter te specificeren of deze verplicht is en wat het formaat en bereik zijn. Daar zijn dan aanvullende regels voor nodig.

**Comment by lvdbrink** [comment]
Aanvulling (met dank aan Marielle van Vliet, TNO): 

Een ander nadeel van het modelleren van de veldparameters als attributen is dat dit een beperkte lijst is. Op deze manier is het niet mogelijk om andere veldparameters aan te leveren, die in het kader van een onderzoek wel gemeten zijn maar niet in deze lijst voorkomen. In het veld worden steeds vaker andere analyses uitgevoerd (bijv. nitraat, sulfaat, ..). Een codelijst zou flexibeler zijn om uit te breiden.

**Comment by AnnitaVijverberg** [comment]
Veldparameters zijn nu goed gemodelleerd. Wel moet er uiteindelijk consistentie zijn in de manier waarop veld- en labparameters worden gemodelleerd en hoe dit op andere plekken in de BRO wordt gedaan.

**Comment by AnnitaVijverberg** [comment]
Reactie van Nanko (Provincie Noord-Holland) De resultaten van de veldmeting zijn nu als aparte attributen gemodelleerd. Is het niet beter ze te modelleren als parameter van een generiek attribuut?
