### ISSUE TITLE
Tekstueel paragraaf 3.5

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#142]
## Type issue
Toevallig gezien

## Waar
[Paragraaf 3.5](https://broprogramma.github.io/GAR/#inspire)

## Samenvatting
Er staat: "Dit wordt voor dit registratieobject geïmplementeerd middels een mapping van het gegevensmodel van het registratieobject **Grondwatermonitoringnet** op het gegevensmodel van het INSPIRE-thema."

**Grondwatermonitoringnet** moet hier denk ik **Grondwatersamenstellingsonderzoek** zijn.

**Comment by AnnitaVijverberg** [comment]
Klopt. Het is aangepast en zichtbaar in de volgende versie.
