### ISSUE TITLE
Regels voor ontbreken veldmetingen

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#15]
Zo mogelijk definiëren we nog regels voor het ontbreken van veldmetingen. Bijvoorbeeld: "Als zuurstofgehalte geen waarde heeft, moet er een bijzonderheid zijn opgenomen die aangeeft dat de doorstroomcel niet gebruikt kon worden". 

(Overigens kent de bijzonderhedenlijst deze waarde nog niet; deze moet dan worden uitgebreid met de mogelijke redenen waarom veldmetingen ontbreken).

**Comment by AnnitaVijverberg** [comment]
De regels zijn zoveel mogelijk toegevoegd. Feedback is welkom
