### ISSUE TITLE
uitvoerder onderzoek

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#16]
Momenteel zitten er drie gegevens in het informatiemodel Grondwatersamenstellingsonderzoek die te maken hebben met de uitvoerder: 

- `uitvoerder onderzoek` bij de klasse `Grondwatersamenstellingsonderzoek `
- `uitvoerder `bij `Veldonderzoek`
- `verantwoordelijk laboratorium` bij `Laboratoriumonderzoek`

Waarschijnlijk is de eerste overbodig, omdat er niet één organisatie verantwoordelijk is voor én het veldonderzoek én het laboratoriumonderzoek, anders dan de bronhouder. De `bronhouder` is al bij het `Registratieobject` opgenomen.

**Comment by rbv305** [comment]
Er zijn laboratoria die hun eigen veldwerkers in dienst hebben. Waterlaboratorium Noord in Glimmen is zo'n lab

**Comment by AnnitaVijverberg** [comment]
zie https://broprogramma.github.io/GAR/#catalogus De uitvoerder bij klasse Grondwatersamenstellingsonderzoek is niet meer opgenomen.

**Comment by AnnitaVijverberg** [comment]
Uit de sprintreview van 30 augustus 2018 kwam naar voren dat er sprake kan zijn van een hoofdaannemer en een onderaannemer van veldwerk en/of lab. In deze situatie wil gebruiker alle uitvoerders weten. Opnieuw bekijken hoe we dit modelleren

**Comment by AnnitaVijverberg** [comment]
Uit het gesprek met Janco van Gelderen: Bij veldwerk en lab zijn meestal twee verschillende uitvoerders. Soms wordt gewerkt met onderaannemers. Soms is er een partij die de opdracht van provincies heeft gekregen en schakelt die partij voor veld en/of lab weer anderen in. Een overkoepelende partij wordt met name ingeschakeld als de bronhouder ook het beoordelen van de kwaliteit uitbesteedt. Een dergelijke uitvoerder past volgens Janco beter bij GMN.

Conclusie is dat we de verantwoordelijke partij voor veld en voor lab vastleggen, geen onderaannemers. Ook geen partij die de beoordeling uitvoert.

**Comment by JancovanGelderen** [comment]
@ Annita, dit is een inderdaad de weergave van ons gesprek

**Comment by AnnitaVijverberg** [comment]
De bovenstaande conclusie is besproken in de sprintreview van 25 okt 2018. Daar kwam naar voren dat Bij lab het ‘verantwoordelijk laboratorium’ heet en bij veld ‘uitvoerder’ dat uis niet consistent. 
De terminologie is nu wel consistent: op beide plekken heet het ' uitvoerder' met als definitie: De identificatie van de organisatie die verantwoordelijk is voor de uitvoering van het veldonderzoek danwel laboratoriumonderzoek.
We sluiten dit issue zoals besproken in de sprintreview van 25 okt 2018
