### ISSUE TITLE
Scope van het registratieobject

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#17]
De scope van het registratieobject Grondwaterkwaliteitsonderzoek is nog niet definitief vastgesteld. De scope is vooralsnog beperkt tot wat er in het kader van Kaderrichtlijn Water, het Landelijk Meetnet Grondwaterkwaliteit, het Provinciaal Meetnet Grondwaterkwaliteit of de monitoring van verdroging gemeten wordt.

**Comment by AnnitaVijverberg** [comment]
De scope is vastgelegd in het scopedocument.
De laatste versie is [hier](https://github.com/BROprogramma/GAR/tree/gh-pages/docs) te vinden.
