### ISSUE TITLE
Definities van codelijsten ontbreken

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GAR#19]
Dit is een issue als gevolg van techniek. De definities zijn wel aanwezig maar worden in de catalogus niet getoond. We werken aan een oplossing.

**Comment by AnnitaVijverberg** [comment]
Om op dit moment toch de definities van de codelijst BijzonderhedenVeldonderzoek te kunnen bekijken, is hij hier bijgevoegd. 
[Toelichtng codelijst BijzonderhedenVeldonderzoek.pdf](https://github.com/BROprogramma/GAR/files/2079826/Toelichtng.codelijst.BijzonderhedenVeldonderzoek.pdf)

**Comment by rbv305** [comment]
Zijn de weersomstandigheden nog relevant ?

**Comment by MarijkeHuijgen** [comment]
Dit probleem is opgelost. Ik sluit daarom dit issue.

**Comment by MarijkeHuijgen** [comment]
Heropend, probleem lijkt toch nog te bestaan.

**Comment by lvdbrink** [comment]
Zie ook https://github.com/Imvertor/Imvertor-Maven/issues/34

**Comment by AnnitaVijverberg** [comment]
Ik sluit hem omdat het probleem is opgelost. 
Het probleem ontstaat wanneer codelijst-items geen stereotype hebben. Door ze het stereotype Enumeratiewaarde te geven wordt de definitie van de items wel meegenomen in de catalogus.
