### ISSUE TITLE
Opname in BRO van aantoonbaarheids-, bepaalbaarheids-, en/of rapportagegrens

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#23]
Momenteel staat in de werkversie van het informatiemodel GAR alleen de rapportagegrens als kenmerk bij [Resultaat laboratoriumwaarneming][1]. Is het een goed idee om ook de aantoonbaarheidsgrens (detectielimiet) en/of bepaalbaarheidsgrens op te nemen? 

Zie [de uitleg van deze termen in de catalogus][2]. 

Tot nu toe is zijn deze gegevens niet opgenomen omdat onze eerste indruk was dat met het gebruik van deze waarde voorzichtig moet worden omgegaan (het valt buiten de geaccrediteerde resultaten v/e lab) en de duiding hiervan bij meer gebruikers vragen op kan roepen dan dat het toegevoegde waarde zou hebben. 

De discussie moet echter nog gevoerd worden na vastgesteld te hebben of de aanwezigheid van een component (ja/nee) een relevant gegeven is.

[1]: https://broprogramma.github.io/GAR/#graph_EAID_0ADEB093_BDEB_47f4_B5B0_8E0E0A003E0D
[2]: https://broprogramma.github.io/GAR/#lab-grenswaarden

**Comment by JvVelthuijsen** [comment]
Zie mijn ander commentaar. Dit lijkt me zeker een bespreekpunt met de laboratoria, want dan zullen de laboratoria 'minder betrouwbare resultaten' moeten leveren.

**Comment by rbv305** [comment]
de toegevoegde waarde is mij niet duidelijk. Sommige beweren dat meetwaarden onder de rapportagegrens iets kunnen zeggen over de werkelijke gehalte van een parameter, zit het vlakbij de rapportagegrens of ver onder. Maar dat zijn dan uitspraken gestoeld op minder betrouwbare metingen dus wat zegt het.

**Comment by JvVelthuijsen** [comment]
Helemaal mee eens.. maar was een speeltje van Bert Veldstra en de inmiddels overleden RIVM-man………

[email footer verwijderd]

**Comment by AnnitaVijverberg** [comment]
Besloten is dat we aantoonbaarheidsgrens en bepalingsgrens niet opnemen. We nemen de rapportagegrens wel op.

**Comment by AnnitaVijverberg** [comment]
We sluiten dit issue zoals besproken in de sprintreview van 25 okt 2018

**Comment by AnnitaVijverberg** [comment]
Het gebruik van de aantoonbaarheidsgrens valt buiten de geaccrediteerde resultaten van een laboratorium en dit gegeven heeft geen grote hergebruikswaarde. Daarom nemen we deze grens niet op.
De bepaalbaarheidsgrens wordt niet door alle laboratoria gebruikt. Van de drie grenzen is deze het minst gebruikt en wordt daarom niet opgenomen.
