### ISSUE TITLE
Wel/niet opnemen metingen onder rapportagegrens

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#24]
Meetwaarden tussen aantoonbaarheidsgrens en rapportagegrens (zie [definities][1]) kunnen in de praktijk in bijzondere gevallen geleverd worden door het laboratorium aan de opdrachtgever. Deze meetwaarden zijn echter minder betrouwbaar dan meetwaarden boven rapportagegrens. Gebruik ervan is 'op eigen risico'; het laboratorium neemt hier geen verantwoording voor. 

Discussiepunt: is het wel/niet wenselijk om deze meetwaarden in de BRO op te nemen, eventueel met een indicatie van de betrouwbaarheid? 

Bijkomende vraag: de definities van aantoonbaarheidsgrens, bepalingsgrens en rapportagegrens spreken van een bepaalde betrouwbaarheid. Is er binnen het werkveld iets afgesproken over wat die betrouwbaarheid is? Wordt dit misschien afgevangen met het vastleggen van de meetonzekerheid in aanbestedingen?

[1]: https://broprogramma.github.io/GAR/#lab-grenswaarden

**Comment by AnnitaVijverberg** [comment]
Nu worden waarden onder de rapportagegrens gerapporteerd als <[RG]. Dus in het geval de rapportagegrens 2 is. Wordt nu ingevuld <2

**Comment by JvVelthuijsen** [comment]
In het verleden zijn door het laboratorium meetwaarden boven de aantoonbaarheidsgrens maar onder de rapportagegrens in excell aangeleverd. Resultaten zijn minder betrouwbaar, vraag is dan ook of dit wenselijk is.
Hierdoor krijg je ook verschillen tussen het papieren analysecertificaat (bv < 0,3) en het digitale gehalte in de excell-tabel (bv 0,28). Gaat zeker tot verkeerde interpretaties leiden.

**Comment by AnnitaVijverberg** [comment]
Uit de sprintreview van 30 augustus 2018:
- Wordt nu variabel wel/niet gerapporteerd
- Voorgesteld wordt om hiervoor een label ‘onder rapportagegrens’ te gebruiken
- Rapportagegrens zelf wordt ook geleverd door lab, maar is niet relevant bij metingen hoger dan rapportagegrens.
- Besluit: Rapportagegrens is onderdeel van de standaard
- Verkend wordt of ook aantoonbaarheidsgrens moet worden geregistreerd. Lijkt minder relevant;

**Comment by AnnitaVijverberg** [comment]
Besloten is dat we aantoonbaarheidsgrens en bepalingsgrens niet opnemen. We nemen de rapportagegrens wel op.

**Comment by AnnitaVijverberg** [comment]
Uit de sprintreview van 25 oktobver:‘ Een attribuut 'onder rapportagegrens ja/nee’ is overbodig. Janco pleit ervoor om de rapportagegrens voor de toekomst verplicht te maken, ook omdat de rapportagegrens verhoogd kan zijn. Het is een belangrijk gegeven, waardevol.
Rapportagegrens kan verschillen tussen GAR’s. Voor historische gegevens is het niet meer (altijd) te achterhalen.
In de vergadering wordt besloten:
- Rapportagegrens in IMBRO verplicht. Voor IMBRO/A niet.
- Attribuut 'onder rapportagegrens ja/nee' verwijderen
- Zowel waarde als rapportagegrens kunnen aangeleverd worden waarbij minstens 1 van beide gevuld moet zijn.
