### ISSUE TITLE
regels ionenbalans

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GAR#25]
In de berekening van de ionenbalans worden diverse stoffen gebruikt. Wordt voor al deze stoffen altijd opdracht gegeven ze te meten (kardinaliteit 1) of worden sommige niet altijd gemeten? Dit moet resulteren in de regels voor de ionenbalans.

**Comment by JvVelthuijsen** [comment]
Ionenbalans werd tot 2014 door het lab gerapporteerd op het analysecertificaat, Vanaf 2015 niet meer.
Het bepalen van de ionenbalans is duidelijk een 'tool' voor de bronhouder en niet voor de LV-BRO

**Comment by AnnitaVijverberg** [comment]
Ionenbalans zou onderdeel uit kunnen maken van de coherentiekarakteristieken. Het onderdeel coherentiekarakteristiek is (voorlopig) niet opgenomen in GAR.

**Comment by JvVelthuijsen** [comment]
Ionenbalans is een eigen, interne controle die de bronhouder zelf kan uitvoeren… mijn inziens zeker NIET opnemen in de BRO.

Jack van Velthuijsen

**Comment by rbv305** [comment]
Eens met Jack.
