### ISSUE TITLE
Compleetheid BijzonderhedenVeldonderzoek

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GAR#29]
Feedback Provincies: BijzonderhedenVeldonderzoek. “Dit wordt zelden genoteerd op het veldformulier > lijkt me niet zo zinvol dit in de BRO te willen beleggen. Daarnaast zou je kunnen stellen dat dit onderdeel uitmaakt van de validatie door de bronhouder.”

**Comment by AnnitaVijverberg** [comment]
Dat bijzonderheden tot nu toe niet genoteerd worden is relevant voor IMBRO/A, niet voor IMBRO. Het gegeven geeft de gebruiker informatie over de eventuele problemen die zich bij de bemonstering hebben voorgedaan.

**Comment by lvdbrink** [comment]
N.a.v. sprint review 19 juli heropend. 

Tijdens deze sprint review kwam naar voren dat het überhaupt opnemen van bijzonderheden misschien te ver gaat. Dit levert extra administratielast op maar weinig meerwaarde. Alvorens eventueel de Bijzonderheden veldonderzoeknorm te schrappen, willen we de gebruikerskant ook horen. Als er van die kant goede redenen zijn om deze informatie in de BRO te hebben dan speelt dat mee. 

Wie deze gebruikers zijn wordt uitgezocht. De grootste gebruiker zijn de provincies zelf voor hun rapportages. Toch worden wel grondwaterkwaliteitsgegevens opgevraagd, maar niet erg frequent. 

Brabant heeft deze data in een eigen portaal gepubliceerd en nog nooit vragen gekregen over omstandigheden of afwijkingen. Als de BRO bijzonderheden voor veld opneemt, moet het voor lab ook. Dit is ook het voornemen van het standaardisatieteam. Echter, bijzonderheden voor laboratoriumgegevens zouden omvangrijk, complexiteitverhogend en kostbaar zijn om in te winnen. Eigenlijk vallen bijzonderheden en afwijkingen onder de processtap Analyse & beoordelen: de uitvoerders melden bijzonderheden aan de bronhouder, die beoordeelt of dit van invloed is. 

Dit punt wordt besproken met gebruikers, minimaal RIVM.

**Comment by AnnitaVijverberg** [comment]
Uit de sprintreview van 25 oktober 2018:
Nanko: Ik wil aanraden om hierbij nog te wachten op het Labels-onderzoek. Terminologie daaruit kan ook eventueel bij veldonderzoek gebruikt worden.
Janco: Ik verwacht niet dat het niet veel gevuld gaat worden. De vraag is wat dit gaat toevoegen. Want heel veel zullen leeg blijven.
Nanko: Er is een verschil tussen meegeven aan de bronhouder en meegeven aan de BRO. Afwijkend filter
bijvoorbeeld, in dat geval zal de bronhouder het corrigeren voordat hij de gegevens aanlevert aan de BRO.
N.B. Er zijn inhoudelijk verschillende bijzonderheden op de codelijst: sommige weten ze in veld al, andere komen uit validatieproces. Sommige zeggen iets over het hele onderzoek en sommige over een monster.
BESLUIT: We wachten de uitkomst van het labelings-onderzoek af, daarna besluiten we over bijzonderheden veldonderzoek.

**Comment by AnnitaVijverberg** [comment]
Uit de sprintreview van 17 januari 2019 kwam naar voren dat de items van bijzonderheden veldonderzoek wenselijk zijn om op te nemen. Ze geven de gebruiker informatie over constateringen tijdens de monstername en veldmetingen die afwijkend zijn van de procedure. Veldwerkers maken hier notities van. Het is zonde die niet op te nemen.

**Comment by AnnitaVijverberg** [comment]
EGVMoeilijkTeBepalen is een van de items op de codelijst van BijzonderhedenVeldonderzoek. We hebben van TNO de reactie gekregen dat niet alleen EGV moeilijk te bepalen kan zijn. "Bij zuurstof en pH is dat veel waarschijnlijker dan bij EGV. En ook de temperatuur kan moeilijk te bepalen zijn als het erg warm is, de slang lang is, etc."
We zouden daarom in de codelijst naast EGVMoeilijkTeBepalen ook kunnen opnemen:
- O2MoeilijkTeBepalen
- pHMoeilijkTeBepalen
- tempMoeilijkTeBepalen

**Comment by AnnitaVijverberg** [comment]
Reactie op het bovenstaande van Deltares: Mijn ervaring is dat EGV en pH niet moeilijk te meten te zijn in het veld. Ik kan mij niet herinneren dat hier ooit opmerkingen over gemaakt zijn. 
Zuurstof kan lastig te meten zijn wanneer de peilbuis niet genoeg water geeft maar zoals je in de bijlage kan lezen heeft een slecht lopende peilbuis op veel zaken invloed.
Temperatuur lastig te meten omdat het warm weer is, daar kan ik mij wel iets bij voorstellen maar de slang te lang vind ik een slechte reden, kort de slang dan in, gaarne geen rollen slangmateriaal op het maaiveld tijdens het bemonsteren. 

Wanneer je er voor kiest om EGVMoeilijkTeBepalen in de tabel op te nemen dan rechtvaardigt dit om ook de volgende drie codes op te nemen.
- O2MoeilijkTeBepalen – reden: slecht lopende peilbuis – waarde wordt niet stabiel of blijft te hoog
- pHMoeilijkTeBepalen – reden: water bepaalde film op het diafragma van de pH-elektrode – waarde niet stabiel
- tempMoeilijkTeBepalen – reden: extreem warm weer i.c.m. slecht lopende peilbuis – temperatuur van het grondwater lijkt te hoog

**Comment by AnnitaVijverberg** [comment]
Reactie van veldwerker van het RIVM:
Bij de bemonstering van grondwaterputten stroomt vrijwel altijd helder water door een doorstroomcel, waar de elektrodes voor de genoemde metingen in steken. 

Wij ervaren met de pH en EC meting nauwelijks problemen. Wel kan er bij roestig of venig water gedurende de dag een ‘filmlaagje’op de elektrodes neerslaan, waardoor je een duidelijk verschil tussen de metingen in de standaardvloeistof aan het begin en het eind van de meetdag ziet. Maar hiervoor zou ik niet zeggen dat EC of pH moeilijk te bepalen is; eerder een vraag los hiervan of het water kleurloos of een bepaalde kleur heeft.

Calibratie gegevens aan het begin en eind van de dag zijn wat dit betreft dus wel essentieel. Tijdens ons laatste gesprek verbaasde het mij dat een provincie geen einde dag controle metingen deed. Hiermee kan je juist ‘slechte’ meetwaarden opsporen.

De zuurstof meting blijft een geval apart. Zuurstof meters zijn erg gevoelig en veel veldwerkers hebben weinig vertrouwen in de betrouwbaarheid van de metingen. Als de zuurstof moeilijk te bepalen is, heeft het ook hier weer eerder met de meter (controlemetingen zijn weer van belang) dan met de omstandigheden te maken.

De temperatuur in de doorstroomcel kan inderdaad flink afwijken van de watertemperatuur in de put. Wij meten deze allebei. De watertemperatuur in de doorstroomcel is wel belangerijk omdat deze wat zegt over de Ec waarde, welke ook in de doorstroomcel wordt gemeten. Als je met moeilijk te bepalen bedoeld dat je de echte grondwatertemperatuur wilt weten terwijl je in de doorstroomcel meet dan klopt dat. De gemeten waarde zal zeker bij extreme buitentemperaturen enkele graden afwijken van de grondwatertemperatuur.

Wellicht is dit niet een duidelijk wel/niet verhaal. Eigenlijk komt het erop neer dat ik los van de temperatuur de vraag niet zou toevoegen. Maar de controlemetingen zijn wel essentieel om de betrouwbaarheid van gemeten waarden te kunnen bepalen.

**Comment by AnnitaVijverberg** [comment]
We hebben besloten om EGVMoeilijkTeBepalen, O2MoeilijkTeBepalen en pHMoeilijkTeBepalen niet op te nemen. De reden dat deze parameters niet goed bepaald kunnen worden ligt bij de apparatuur, niet bij de omstandigheden. In de codelijk staat al: afwijkingInMeetapparatuur met als definitie: De gebruikte meetapparatuur had een te groot verloop. De meetapparatuur wordt dagelijks in ieder geval een keer gekalibreerd. In de loop van de dag kan de meetapparatuur een groeiende afwijking gaan vertonen. Daarnaast nemen we op afwijkendeKleur omdat dit bij EGV en pH de oorzaak kan zijn van het afwijken van de meetaparatuur.

Verder nemen we op: temperatuurMoeilijkTeBepalen met in de definitie dat dit geldt bij metingen in de de doorstroomcel en dat dit voor kan komen als te temeratuur extreem is en de doorstroomsbnelheid laag.

**Comment by AnnitaVijverberg** [comment]
[Dit](https://broprogramma.github.io/GAR/#detail_class_Model_BijzonderheidVeldonderzoek) is nu de lijst met bijzonderheden veldonderzoek.

**Comment by rbv305** [comment]
Als ik op het woord  "Dit" klik kom ik uit op het informatiemodel grondwatersamenstellingsonderzoek uit. Klopt dat ? Ik verwacht nl lijst bijzonderheden veldonderzoek.

**Comment by AnnitaVijverberg** [comment]
Vermoedelijk browser pericelen waardoor je niet op de lijst uitkomt. Voor de volledigheid hierbij:
![bijzonderheidveldonderzoek](https://user-images.githubusercontent.com/38854805/52866432-edde1a00-313e-11e9-993a-69979da64b8f.jpg)

**Comment by rbv305** [comment]
yes, ik gebruik nu google chrome en nu krijg ik wel de lijst

**Comment by rbv305** [comment]
wat ik ook vaak teruggemeld krijg van veldwerkers is dat de toeloop van het grondwater moeilijk verloopt waardoor bemonstering soms te lang duurt.

**Comment by AnnitaVijverberg** [comment]
We hebben onderzocht of het noodzakelijk is een aanvullende bijzonderheid op te nemen of dat hij wordt afgedekt door een andere bijzonderheid die wel op de lijst staat.

[veldmedewerker RIVM] "Als de toestroom slecht is ga je dat merken aan dat het peil te veel daalt. Als het heel slecht toestroomt ga je soms alleen nog maar gebruik maken van een laag debiet slangenpomp. Als het in het uiterste geval niet lukt om het peil minder dan 2 meter te laten zakken met de onderwater pomp, moeten we wel de slangenpomp gaan gebruiken. Dat gebeurt weinig en is zeer tijdrovend, omdat je met een maximaal debiet van 0,5 liter per seconde werkt dan. Maar ja het is het enige alternatief."
Dit is een van de redenen waarom het pomptype is opgenomen.

[veldexpert Deltares] Er wordt al diverse keren naar een slechtlopende buis verwezen, in principe kan je het al herleiden. Een apart item met ‘slecht watertoeleverende peilbuis’ kan wat mij betreft geen kwaad omdat het dan snel inzichtelijk is bij raadpleging van de BRO.

BRO standaardisatieteam heeft op basis hiervan besloten dat we deze bijzonderheid niet toevoegen. Mocht er in de, spoedig startende, publieke consultatie aanvullende informatie naar voren komen kunnen we dit heroverwegen.
Sander, als je het niet eens bent met onze conclusie en toch graag de extra bijzonderheid toegevoegd wilt, kun je deze feedback aandragen bij publieke consultatie.

**Comment by AnnitaVijverberg** [comment]
Mariëlle van Vliet, TNO:
## Type issue
Publieke consultatie

## Beschrijving
Bijzonderheid afwijkendeKleur: "Het grondwater is niet doorzichtig, maar heeft bijvoorbeeld een roestige of venige kleur. Hierdoor kan gedurende de dag een filmlaag op de elektrodes in de meetapparatuur neerslaan. Dit kan de meting van de geleidendheid (EGV/EC) en de pH beïnvloeden."
Is geel of bruin, transparant een niet-afwijkende kleur (a la bier)? Door hoog DOC kan grondwater wel een natuurlijke kleur hebben.
AfwijkendeKleur impliceert dat kleur anders is dan verwacht, terwijl het niet ongewoon is dat het monster een kleur heeft.

**Comment by AnnitaVijverberg** [comment]
Jasper Griffioen, TNO:
## Type issue
Publieke consultatie

## Beschrijving
Bijzonderheid afwijkendeKleur: "... meting van de geleidendheid (EGV/EC) en de pH beïnvloeden"
Dit is geen Nederlands woord. Het moet geleidbaarheid zijn.

## Oplossingsrichting
Het moet geleidbaarheid zijn.

**Comment by AnnitaVijverberg** [comment]
Mariëlle van Vliet, TNO:
## Type issue
Publieke consultatie

## Beschrijving
Bijzonderheid contaminatieDoorVerbrandingsmotor: "Dit kan gebeuren als een verbrandingsmotor wordt gebruikt tijdens het bemonsteren. Men wordt geacht benedenwinds te gaan staan van deze motor."
Benedenwinds is fout

## Oplossingsrichting
Het moet zijn 'bovenwinds'

**Comment by AnnitaVijverberg** [comment]
Mariëlle van Vliet, TNO:
## Type issue
Publieke consultatie

## Beschrijving
Bijzonderheid filterBelucht" "De peilbuis liep tijdens de monstering slecht en het filter is drooggevallen, maar er is geen lucht in het monster terechtgekomen."
Het gaat hier nog niet over monster, dat is in het volgende veld 'monsterBelucht'. 
Hier wil je dus alleen melden dat het filter is drooggevallen. 

## Oplossingsrichting
Tekst aanpassen: 
"De peilbuis liep tijdens de monstering slecht en het filter is drooggevallen."

**Comment by AnnitaVijverberg** [comment]
Jasper Griffioen, TNO:
## Type issue
Publieke consultatie

## Beschrijving
Bijzonderheid grondwaterstandTeveelGedaald: "De grondwaterstand is tijdens en na het voorpompen met meer dan 50cm verlaagd."
50cm is foutief geschreven.

## Oplossingsrichting
tussen waarden en eenheden horen spaties!! Menig student moet ik hier ook op wijzen!
Uitzondering is 25oC, ofwel 25 graden Celcius

**Comment by AnnitaVijverberg** [comment]
Roeland Heuff, SIKB
## Type issue
Publieke consultatie

## Beschrijving
Een aantal andere waarnemingen die gebruikelijk zijn zitten bij jullie in ‘bijzonderheidveldonderzoek’. Bij ons zitten deze onder de waarnemingen. Uitwisseling via een codelijst zoals in jullie model voorgesteld sluit niet aan op wat gangbaar is en zal lastig zijn om te realiseren. De inhoud van jullie lijstje sluit ook niet helemaal lekker aan en is niet helemaal volledig, sluit niet aan op de onderliggende normen. Zie sheet waarnemingenlijst bijgevoegd om te zien hoe dit binnen Metingen is opgelost. Geur en troebelheid zien we niet terug.

**Comment by AnnitaVijverberg** [comment]
We hebben afwijkende kleur verwijderd. In plaats daarvan hebben we aan de lijst veldwaarnemingen hoofdkleur, bijkleur en kleursterkte toegevoegd. Voor hoofd- en bijkleur wordt een kleur gekozen uit (dezelfde) kleurencodelijst, overgenomen van SIKB/IHW. Voor kleursterkte wordt ook uit een codelijst gekozen.
Overige punten ook opgelost.
We geven aan SIKB een lijstje door met verzoeken voor toevoegingen van veldwaarnemingen.
Geur is bij SIKB een 'DescriptionResult' m.a.w. een beschrijving, vrij tekstveld. Die vermijden we in de BRO. Daarom en omdat de stakeholders niet gevraagd hebben naar het opnemen van geur, geur (vooralsnog) niet opgenomen.
