### ISSUE TITLE
Compleetheid codelijst Bijzonderheden veldonderzoek

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#3]
De mogelijke waarden van de codelist [AfwijkingVeldonderzoeknorm][1] moeten nog worden getoetst bij experts. Momenteel staan er in deze lijst afwijkingen van de norm. Mogelijk moet deze lijst nog worden aangevuld met andere omstandigheden, die relevant zijn, maar niet een expliciete afwijking op de norm vormen. Als er zulke omstandigheden zijn worden deze ook in de lijst opgenomen. De lijst moet dan wellicht een andere naam krijgen. 

Het is de bedoeling om GEEN vrij tekstveld op te nemen voor het noemen van overige bijzonderheden / omstandigheden die tijdens het veldwerk optraden. Het is dus wel belangrijk dat deze lijst zo volledig is als nodig is. 

[1]: https://broprogramma.github.io/GAR/#detail_class_Model_BijzonderhedenVeldonderzoek

**Comment by lvdbrink** [comment]
Vraag hierbij is nog: Is de constatering van afwijkingen veldwerk ten opzichte van labeisen BRO informatie (i.e. voor gebruiker relevant) en wie stelt die afwijking vast? De veldmedewerker? Of de opdrachtgever?

**Comment by lvdbrink** [comment]
De mogelijke waarden van de codelist AfwijkingVeldonderzoeknorm zijn getoetst bij experts. Deze input moet nog worden verwerkt in deze Gegevenscatalogus. 

De veldmederwerker noteert bijzonderheden aka afwijkingen.

**Comment by lvdbrink** [comment]
Inmiddels is de input verwerkt in de concept gegevenscatalogus, zie [hier][1].

NB in plaats van 'afwijkingen' spreken we nu van 'bijzonderheden'. 

[1]: https://broprogramma.github.io/GAR/#detail_class_Model_BijzonderhedenVeldonderzoek

**Comment by AnnitaVijverberg** [comment]
Veldmedewerker RIVM;
"Bij de bemonstering van grondwaterputten stroomt vrijwel altijd helder water door een doorstroomcel, waar de elektrodes voor de genoemde metingen in steken.
Wij ervaren met de pH en Ec meting nauwelijks problemen. Wel kan er bij roestig of venig water gedurende de dag een ‘filmlaagje’ op de elektrodes neerslaan, waardoor je een duidelijk verschil tussen de metingen in de standaardvloeistof aan het begin en het eind van de meetdag ziet. Maar hiervoor zou ik niet zeggen dat ec of pH moeilijk te bepalen is; eerder een vraag los hiervan of het water kleurloos of een bepaalde kleur heeft.

Calibratie gegevens aan het begin en eind van de dag zijn wat dit betreft dus wel essentieel. Tijdens ons laatste gesprek verbaasde het mij dat een provincie geen einde dag controle metingen deed. Hiermee kan je juist ‘slechte’ meetwaarden opsporen.

De zuurstof meting blijft een geval apart. Zuurstof meters zijn erg gevoelig en veel veldwerkers hebben weinig vertrouwen in de betrouwbaarheid van de metingen. Als de zuurstof moeilijk te bepalen is, heeft het ook hier weer eerder met de meter (controlemetingen zijn weer van belang) dan met de omstandigheden te maken.

De temperatuur in de doorstroomcel kan inderdaad flink afwijken van de watertemperatuur in de put. Wij meten deze allebei. De watertemperatuur in de doorstroomcel is wel belangrijk omdat deze wat zegt over de Ec waarde, welke ook in de doorstroomcel wordt gemeten. Als je met moeilijk te bepalen bedoeld dat je de echte grondwatertemperatuur wilt weten terwijl je in de doorstroomcel meet dan klopt dat. De gemeten waarde zal zeker bij extreme buitentemperaturen enkele graden afwijken van de grondwatertemperatuur."

Deltares:
"Mijn ervaring is dat EGV en pH niet moeilijk te meten te zijn in het veld. Ik kan mij niet herinneren dat hier ooit opmerkingen over gemaakt zijn.
Zuurstof kan lastig te meten zijn wanneer de peilbuis niet genoeg water geeft maar zoals je in de bijlage kan lezen heeft een slecht lopende peilbuis op veel zaken invloed.
Temperatuur lastig te meten omdat het warm weer is, daar kan ik mij wel iets bij voorstellen maar de slang te lang vind ik een slechte reden, kort de slang dan in, gaarne geen rollen slangmateriaal op het maaiveld tijdens het bemonsteren.
Wanneer je er voor kiest om EGVMoeilijkTeBepalen in de tabel op te nemen dan rechtvaardigt dit om ook de volgende drie codes op te nemen.
- O2MoeilijkTeBepalen – reden: slecht lopende peilbuis – waarde wordt niet stabiel of blijft te hoog
- pHMoeilijkTeBepalen – reden: water bepaalde film op het diafragma van de pH-elektrode – waarde niet stabiel
- tempMoeilijkTeBepalen – reden: extreem warm weer i.c.m. slecht lopende peilbuis – temperatuur van het grondwater lijkt te hoog"
