### ISSUE TITLE
AfwijkingLaboratoriumprocedure (en methode)

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GAR#31]
Feedback Provincies over Afwijking laboratorium procedure. “Ik vraag me af of dit nu wel moet worden vastgelegd, in de praktijk leidt dit vrijwel altijd tot een verhoogde rapportagegrens en die wordt toch sowieso vastgelegd bij elke meting. Dus waarom dan achterliggende reden vastleggen, het gaat uiteindelijk alleen om de meetwaarde en de rapportagegrens die bekend moeten zijn. Analysemethode: Het lijkt me veel zinvoller om eenmalig bij de meetronde een lijst met gebruikte analysetechnieken per parameter aan te leveren dan deze bij elke meting op te slaan. Dit zit nu ook niet in IHW-bestand. Kan wel afzonderlijk per ronde vermoedelijk nog worden aangeleverd door de provincies tot op zekere hoogte (2006 vermoed ik). Omstandigheden: Dit lijkt me een vaag attribuut."

**Comment by AnnitaVijverberg** [comment]
Komt terug als we aan lab-parameters werken

**Comment by rbv305** [comment]
Wordt hiermee ook bedoelt dat een lab afwijkt van een nen-norm bij het analyseren van een parameter ? Dat hoeft dan niet perse tot een verhoogde rapportagegrens te leiden. De term omstandigheden kan inderdaad heel breed opgevat te worden, tot en met het humeur van de analist. Maar ik neem aan dat de labs een lijst hanteren met relevante omstandigheden die mogelijk van invloed kunnen zijn op het resultaat.

**Comment by AnnitaVijverberg** [comment]
ik sluit deze omdat er 2 issues zijn over hetzelfde onderwerp. Vanuit issue https://github.com/BROprogramma/GAR/issues/4 een link opgenomen naar dit issue zodat deze informatie niet vergeten wordt.
