### ISSUE TITLE
Temperatuur en Temperatuur in situ / PlaatsVeldmeting

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GAR#33]
Feedback Provincies over Temperatuur en Temperatuur in situ: "Feitelijk is er in de IHW data nu voor beide dat dit in situ is. Temperatuur in lab is namelijk ex situ. Het lijkt me ook geen relevante parameter om het verschil in meting in de peilbuis of in doorstroomcel aan te geven. Ik zou voorstellen dat er alleen temperatuur in situ wordt vastgelegd (als veldmeting).”

**Comment by AnnitaVijverberg** [comment]
Huidig IHW is niet leidend. Blijkbaar is de inhoud van de term in-situ contextgevoelig. De BRO zal daar rekening mee houden.

**Comment by AnnitaVijverberg** [comment]
HWL over het verschil tussen temperatuur en temperatuur in situ:
Het zou geen verschil mogen maken in waarde of je in de put meet of bij oppompen. Bij oppompen moet je namelijk voldoende water hebben opgepompt tot een aantal parameters stabiel zijn.

**Comment by AnnitaVijverberg** [comment]
TNO over temperatuur in-situ. Temperatuur wordt volgens mij nooit in-situ gemeten. EC en pH werden in het verleden nog wel eens in-situ (dus op diepte in het filter) gemeten, maar ik vraag me af of er nog partijen zijn die deze meetapparatuur hebben.

**Comment by lvdbrink** [comment]
Voor de volledigheid: RIVM heeft aangegeven dat zij de grondwatertemperatuur in-situ (dus in het filter) meten. Ook het O2-gehalte wordt door RIVM in-situ gemeten.

**Comment by AnnitaVijverberg** [comment]
We hebben de in het veld gemeten gegevens nu zo gemodelleerd dat per parameter naast de waarde ook aangegeven kan worden of de bepaling in situ is gedaan of niet. Als een parameter zowel in als ex situ is gemeten kunnen beide metingen nu opgenomen worden.

**Comment by AnnitaVijverberg** [comment]
Onderstaande quote van een veldmedewerker van het RIVM ging over bijzonderheden veldonderzoek maar is ook relevant voor in/ex situ:
"De temperatuur in de doorstroomcel kan inderdaad flink afwijken van de watertemperatuur in de put. Wij meten deze allebei. De watertemperatuur in de doorstroomcel is wel belangerijk omdat deze wat zegt over de Ec waarde, welke ook in de doorstroomcel wordt gemeten. Als je met moeilijk te bepalen bedoeld dat je de echte grondwatertemperatuur wilt weten terwijl je in de doorstroomcel meet dan klopt dat. De gemeten waarde zal zeker bij extreme buitentemperaturen enkele graden afwijken van de grondwatertemperatuur."

**Comment by AnnitaVijverberg** [comment]
Roeland Heuff, SIKB
## Type issue
Publieke consultatie

## Beschrijving
PlaatsVeldmeting (filterdiepte of in doorstroomcel) is voor SIKB geen herkenbaar veld. Wat is de relevantie. In de regel niet op filterdiepte

**Comment by AnnitaVijverberg** [comment]
Mariëlle van Vliet, TNO:
Jasper Griffioen, TNO
## Type issue
Publieke consultatie

## Waar
1.1.6.3 Attribuutsoort details Resultaat veldmetingen plaats veldmeting, definitie

## Beschrijving
"in de doorstroomcel."
Soms werk je in een emmer. Zeker ook voor bemonstering van gassen.

## Oplossingsrichting
Definitie aanpassen.

**Comment by AnnitaVijverberg** [comment]
Het gegeven dat is gemeten op filterdiepte danwel in een doorstroomcel is vrijwel alleen relevant bij het meten van de temperatuur bij warm weer, als een lage pompsnelheid gebruikt moet worden, kan de temperatuur in een doorstroomcel significant afwijken van de temeratuur van het grondwater (op filterdiepte). We gaan dit attribuut verwijderen omdat dit voor SIKB/Aquo geen herkenbaar veld is. Dat maakt de mapping op de BRO lastig. Bovendien is RIVM de enig (voor zover wij hebben gehoord) die op filterdiepte meet en de relevantie is er alleen in uitzonderlijke situaties.  Voor de uitzonderlijke situatie is er een bijzonderheid/attribuut dat specifiek gaat over de situatie waarbij grondwater is opgewarmt. Deze bijzonderheid wordt een attribuut en blijft gehanthaafd.
