### ISSUE TITLE
Parameters wel/niet verplicht

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GAR#36]
Feedback Provincies: “Maak geen enkele meting (veld of lab) ‘verplicht’. Bronhouders hebben voldoende reeds lopende afspraken/documenten waarin ze eventuele verplichtingen onderstrepen.” en 
“Indien de bronhouder bv alleen geïnteresseerd is in chloride, dan wordt alleen chloride gemeten/geregistreerd”

**Comment by AnnitaVijverberg** [comment]
We hebben hier een aantal verdiepende vragen bij namelijk: In welke meetnetten wordt een voorbeeld als chloride gemeten? Wat is in deze gevallen het kader van de inwinning? Wat is het meetprogramma?

**Comment by JvVelthuijsen** [comment]
Er zijn verschillende meetnetten die worden bemonsterd door de provincies. Voor het KRW-meetnet zijn afspraken gemaakt en zijn voor de periode 2015 t/m 2018 vaste pakketten afgesproken met twee laboratoria. In 2016 is daar door PNB o.a. vanaf geweken en zijn aanvullende parameters geanalyseerd. De pakketten zullen in 2019 worden geëvalueerd, zeer waarschijnlijk zullen de pakketten voor 2019 t/m 2022 op detail verschillen.... dus houdt de keuze in parameters vrij

**Comment by AnnitaVijverberg** [comment]
Uit de sprintreview van 30 augustus 2018 over de dynamiek:
- In principe per aanbesteding: per 1-4 jaar wijzigingen; soms ‘losse meetrondes voor specifiek doel’.
- Er is dus een ‘dynamische lijst’ van parameters nodig waaraan nieuwe parameters toegevoegd kunnen worden.
- Voor verkrijgen van inzicht in de toename kunnen oude en nieuwe percelen worden toegestuurd (actie)
- Standaard anticipeert nog niet op nieuwe vorm van meten van GW kwaliteit met sensoren.

**Comment by AnnitaVijverberg** [comment]
Er zijn 2 onderzoeksprocedures in gebruik die verschillend beschrijven welke parameters verplicht gemeten moeten worden in het proces van monsterneming in het veld:

nta8017
"Meet tijdens het voorpompen de pH en EGV en eventueel andere parameters als zuurstof, redox of troebelheid in de doorstroomcel. Veelal zal na het voorpompen van driemaal de natte
stijgbuisinhoud de waarde van de pH en de EGV vrijwel of geheel constant geworden zijn."

nen5744
"Het voorpompen kan worden beëindigd indien:
- minimaal de waarde van het elektrisch geleidingsvermogen (EGV) stabiel is geworden én vijfmaal de inhoud van het filterdeel van de peilbuis is weggepompt
of
- wanneer het elektrisch geleidingsvermogen (EGV) en de opgeloste zuurstof (O2) stabiel zijn geworden
of
- totdat minimaal 3 keer de natte peilbuisinhoud is verwijderd."
Bij nen5744 is het dus niet noodzakelijk parameters te meten tijdens het voorpompen (laatste bullit). 

nta8017 beschrijft het meten van pH, EG, zuurstof, waterstofcabonaat en grondwaterstand maar er kan altijd iets misgaan waardoor één of meer niet gemeten worden.

Darom is ervoor gekozen om de veldparameters geen van allen te verplichten:
- elektrisch geleidingsvermogen [0..1]
- waterstofcarbonaatgehalte [0..1]
- zuurgraad [0..1]
- temperatuur [0..1]
- temperatuur in situ [0..1]
- grondwaterstand [0..1]
- troebelheid [0..1]
- zuurstofgehalte [0..1]

**Comment by AnnitaVijverberg** [comment]
In die sprintreview is besloten de resultaten van veldmeting in het model optioneel op te nemen maar met de regel dat indien gemeten, deze waarden aangeleverd moeten worden.

**Comment by AnnitaVijverberg** [comment]
De bovenstaande opmerking is verwerkt in het conceptueel datamodel. Daarmee kan dit issue worden gesloten.
