### ISSUE TITLE
Compleetheid 'Onderzoeksprocedure'

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GAR#37]
Feedback Provincies over het attribuut ‘onderzoeksprocedure’ bij de entiteit Grondwatersamenstellingsonderzoek. “Er kunnen ook metingen in afwijking (of bij ontbreken) van een onderzoeksprocedure worden gedaan.”

**Comment by AnnitaVijverberg** [comment]
We hebben hier nu een codelijst voor die bevat: ‘Draaiboek KRW’ en ‘Handboek PMG’. Over welke metingen gaat het? In het kader waarvan worden dergelijke metingen gedaan? We moeten bekijken of dergelijke metingen binnen de scope van het (registratieobject) Grondwatersamenstellingsonderzoek (gaan) vallen.

**Comment by rbv305** [comment]
gaat in beide gevallen om de wijze van bemonsteren van het grondwater ten behoeve van de kaderrichtlijn water of het provinciaal grondwaterkwaliteitsmeetnet.

**Comment by AnnitaVijverberg** [comment]
Wat betreft Janco van Gelderen (uit gesprek 4-10-2018) is de onderzoeksprocedure, die nu staat bij entiteit Grondwatersamenstellingsonderzoek, daar overbodig. Deze procedures beschrijven hoe een meetnet opgezet moet worden (dat hoort bij RO grondwatermonitoringnet) en hoe het veldonderzoek uitgevoerd moet worden. Bij de entiteit Veldonderzoek is de bemonsteringsprocedure al opgenomen.
 
Wel zou wat Janco betreft bij laboratoriumonderzoek opgenomen moeten worden welke labmethoden er gebruikt zijn (nu nog niet opgenomen). Bij elke methode worden een aantal stoffen gemeten. Er horen dus meerdere methoden bij een labonderzoek maar niet bij elke individuele stof een andere. De methode zegt iets over de nauwkeurigheid (en is van invloed op de aantoonbaarheidsgrens en de rapportagegrens).

Bij Bemonsteringsprocedure (veld) kan toegevoegd worden bij nta8017: "Uit Handboek Monitoring Grondwaterkwaliteit KRW provincies en RIVM". Niet zeker is of het RIVM deze procedure ook hanteert of een andere (navragen bij het RIVM). Ook moeten we uitzoeken of waterbedrijven zelfde procedures volgen. Indien ook milieuhygiënische metingen worden toegevoegd: hier is een SIKB procedure voor.

**Comment by AnnitaVijverberg** [comment]
[Materiedeskundige van Het Waterlaboratoruim (HWL)] "Het voorschrift van HWL is conform NEN 5744/A1, het beschrijft de monsterneming van grondwater via peilbuizen gericht op chemische parameters."

**Comment by JancovanGelderen** [comment]
@Anita, de weergave van het gesprek met Janco van Gelderen is idd correct

**Comment by AnnitaVijverberg** [comment]
Dit issue kan worden gesloten. Na feedback is besloten de onderzoeksprocedure, die stond bij de entiteit Grondwatersamenstellingsonderzoek, te verwijderen. In het gegevensmodel is de bemonsteringsprocedure (dit bevat ook voorschriften voor ijking van apparatuur) opgenomen bij de entiteit Veldonderzoek en is het Analyseproces (bestaande uit bepalingstechniek, bepalingsprocedure en analysedatum) opgenomen bij het Laboratoriumonderzoek.
