### ISSUE TITLE
compleetheid codelijsten 'kader inwinning' en 'kader aanlevering'

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GAR#38]
Feedback van de Provincies bij kader inwinning en bij kader aanlevering. Hier geldt dat er vaak meer keuzes mogelijk zijn.

**Comment by AnnitaVijverberg** [comment]
We hebben hier aanvullende vragen bij. De BRO verwacht bij beide attributen 1 waarde. Wanneer er nu meer keuzen mogelijk zijn betekent dit dat de codelijsten nog niet juist zijn.

**Comment by rbv305** [comment]
Naar mijn inzicht kun je hier inderdaad 1 waarde invullen. Tenzij je binnen het kader waarin je het onderzoek heb uitgevoerd nog onderscheid wil maken, bijvoorbeeld tussen bestrijdingsmiddelenonderzoek, algemene stoffen, nieuwe stoffen etc.

**Comment by AnnitaVijverberg** [comment]
zie ook: https://github.com/BROprogramma/GAR/issues/12 (één GAR, één doel, één bronhouder?)

**Comment by AnnitaVijverberg** [comment]
In de huidige codelijst staan de volgende mogelijkheden bij 'kader inwinning':
- LMG
- PMGKwaliteit2014_2018
- KRWTT
- KRWOM
- Monitoring verdroging

De codelijst 'kader aanlevering' bestaat uit:
- landelijk grondwaterbeheer
- provinciaal grondwaterbeheer
- natuurbeheer
- gemeentelijke zorgplicht
- richtlijn KRW 2000/60
- drinkwaterwet
- waterwet

**Comment by AnnitaVijverberg** [comment]
Uit het gesprek met Janco van Gelderen: KaderInwinning hoort wellicht thuis bij het registratieobject grondwatermonitoringnet. Naast de genoemde kaders kan hier nog aan toegevoegd worden:
•	Early warning KRW (meetnet moet in 2020 operationeel zijn, samenwerking provincies en waterbedrijven)
•	Projectmatige metingen (bijv. nieuwe stoffen in stedelijk gebied, met uitzondering van milieuhygiënische metingen/saneringen)
De projectmatige metingen zijn metingen die wellicht eenmalig zijn maar ook met lange termijn voor ogen gedaan kunnen zijn. Wellicht worden ze herhaald op een later moment. Het zijn kwaliteitsmetingen van het grondwater waarvan het (wat betreft Janco van Gelderen) zonde zou zijn als ze later niet in de BRO geraadpleegd kunnen worden.
 
Kader aanlevering zou ook bij het registratieobject grondwatermonitoringnet ondergebracht kunnen worden. Hier kan een splitsing gemaakt worden in kwaliteit en kwantiteit kaders, beter dit ook toe te voegen aan de omschrijvingen.

**Comment by JancovanGelderen** [comment]
Inderdaad de weergave zoals besproken

**Comment by AnnitaVijverberg** [comment]
Kader inwinning en kader aanlevering zijn geen onderdeel meer van GAR. Het meetdoel en kader aanlevering zijn opgenomen in GMN (monitoringnet). Een GAR verwijst naar 1 of meer monitoringnetten. Daarnaast is een GAR gekoppeld aan een monitoringbuis in een meetput. Daarmee kan het voorkomen dat de bronhouder van een GAR een andere is dan de bronhouders van de meetput waarin is bemonsterd en een andere is dan de bronhouder van het monitoringnet waaraan het GAR is gekoppeld.
