### ISSUE TITLE
Plaats van implementatie van waardebereiken

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#39]
Het rapport over waardebereiken, en de uitkomsten ervan, hebben een grote nuttige waarde. Het is goed dat op een dergelijk systematische manier de verschillende grenzen, van wat we in de praktijk meten, zijn onderzocht.

Er worden echter vraagtekens gezet bij de plaats van implementatie van de uitkomsten. We willen straks geen “troep” in de BRO opslaan en dat rechtvaardigt tenminste een onder- en bovengrens . Data die een kwaliteitsborging (voorheen “validatie” genoemd) heeft ondergaan, behoort echter per definitie aan dergelijke eisen te voldoen. De vraag is dan ook of je een dergelijke controle in de BRO/bronhoudersportaal moet inbouwen of dat je van oordeel bent dat controles (anders dan technische format-controles) niet in een database thuis horen. Kwaliteitsborging die op twee locaties (bij de bronhouder en bij de BRO) plaats vindt klinkt niet zuiver en als vermenging van verantwoordelijkheden.

**Voorstel waardebereik**
Het voorstel is om de uitkomsten van het waardebereik onderzoek beschikbaar te stellen aan de bronhouders, met daarbij het verzoek om dit te implementeren in de eigen kwaliteitsborging. De provincies geven aan dat graag te doen (en RIVM vermoedelijk ook wel). Daarmee sporen we foutieve waarden al in het voorproces van de kwaliteitsborging op en komt het daarmee niet in de LV-BRO. Daarnaast bied je de bronhouders de mogelijkheid om alsnog gemotiveerd af te wijken van de grenzen van het waardebereik indien er sprake is van een (zeer) bijzondere omstandigheid. Bij de implementatie van het waardebereik door de bronhouder hoeft de BRO tevens geen administratie bij te houden van waardebereiken voor de lange lijst aan stoffen die vrijwel dagelijks langer wordt.

Vanuit de BRO kun je wel aanbieden om voor andere (toekomstige) bronhouders (niet de provincies en RIVM) het waardebereik als “online validator tool” beschikbaar te stellen. Dat past ook mooi bij de faciliterende rol van de BRO. 

Periodiek kan een partij, zoals bijvoorbeeld TNO, het waardebereik als “controle” laten draaien op alles wat er in de LV-BRO aanwezig is. Eventuele geconstateerde afwijkingen kunnen ter verklaring bij de bronhouder worden neergelegd.

**Comment by AnnitaVijverberg** [comment]
Issue wordt gesloten tijdens de sprintreview van 30 augustus 2018. In die meeting is namelijk ook besproken dat het het platform meetnetbeheerders een standaardisatieoplossing aandraagt voor het toepassen van waardebereiken van parameters. Voor het standaardisatieteam is daarmee dit issue komen te vervallen.
