### ISSUE TITLE
Compleetheid codelist bijzonderheden bepalingsprocedure

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#4]
Binnen de BRO willen we een lijst met mogelijke laboratoriumafwijkingen standaardiseren. Laboratoria noemen dit ‘disclaimers’ en hanteren doorgaans zelf ook zo’n lijst, maar er is geen landelijke gestandaardiseerde lijst. Er is wel een lijst binnen het SIKB met ongeveer het zelfde doel, maar op een iets ander niveau. 

De inhoud van de codelist [AfwijkingLaboratoriumprocedure][1] moet nog worden aangevuld op basis van input van laboratoria (disclaimerlijsten) en de SIKB lijst. 

[1]: https://broprogramma.github.io/GAR/#detail_class_Model_BijzonderheidBepalingsprocedure

**Comment by lvdbrink** [comment]
Marielle van Vliet (TNO): 
> Ik weet niet of je dit moet willen, omdat een lab hun specifieke ‘probleem’ wel kwijt moet kunnen.  En als je het doet, dan zeker aansluiten bij SIKB.

**Comment by JvVelthuijsen** [comment]
Dit zeker met de laboratoria bespreken. Hoe zou je dit willen inbouwen, lijkt me meer iets voor de bronhouders, die op basis van relevante disclaimers bepaalde waarden als onbetrouwbaar kunnen markeren.
Disclaimers kunnen zowel afwijkingen als opmerkingen zijn, is ook labspecifiek.

**Comment by AnnitaVijverberg** [comment]
Zie ook issue 31: https://github.com/BROprogramma/GAR/issues/31 met aanvullend commentaar

**Comment by JvVelthuijsen** [comment]
31 en 4 gaan inderdaad over hetzelfde
Ben wel benieuwd of er al overleg is geweest met een lab/labs.
Disclaimers kunnen wel een reden zijn voor de bronhouder om een analyseresultaat als indicatief/niet betrouwbaar te markeren en niet op te laten nemen in de BRO

**Comment by JvVelthuijsen** [comment]
Annita,
Hierbij de info van de percelen 1 t/m 4,provinciaal raamcontract 2015 t/m 2018:
-          Perceel 1: Drempelwaarde stoffen en algemene stoffen
-          Perceel 2: Bestrijdingsmiddelen
-          Perceel 3: Geneesmiddelen en medische stoffen
-          Perceel 4: Overige verontreinigende stoffen
Groeten,

Jack van Velthuijsen
[footer verwijderd]

**Comment by AnnitaVijverberg** [comment]
Uit de sprintreview van 17 januari 2019:
Afwijkingen op de bepalingsprocedure worden soms door laboratoria gerapporteerd als voetnoot, maar we hebben de mogelijkheid om dit aan de BRO aan te leveren eerder uit het model geschrapt. De aanwezigen vinden dit zonde en zien deze mogelijkheid graag terugkeren.

De lijst met [Bijzonderheden Bepalingsprocedure](https://broprogramma.github.io/GAR/#detail_class_Model_BijzonderheidBepalingsprocedure) bevat bijzonderheden c.q. afwijkingen ten opzichte van de gehanteerde bepalingsprocedure, die zich kunnen voordoen tijdens het analyseproces. Het betreft dus bijzonderheden op het niveau van de analyse. Op het niveau van individuele stoffen nemen we geen bijzonderheden op omdat dit een enorme lijst met zeer veel detail kan worden.
Is deze lijst compleet of zijn er op het niveau van de analyse nog meer ' algemene' bijzonderheden mogelijk?

**Comment by rbv305** [comment]
Als ik op de blauwe link druk krijg ik geen lijst

**Comment by AnnitaVijverberg** [comment]
Ik heb hem hier als bijlage toegevoegd. Ik vermoed dat het te maken heeft met je browser [
![bijzonderheidbepalingsprocedure](https://user-images.githubusercontent.com/38854805/52866058-2f21fa00-313e-11e9-9d37-3a20863210e3.jpg)
](url)

**Comment by rbv305** [comment]
yes, als ik in google chrome werk, lukt het wel

**Comment by AnnitaVijverberg** [comment]
Harry van Manen, Rijkswaterstaat:
## Type issue
Publieke consultatie

## Waar
1.2.10. blz. 49,  Codelijst details BijzonderheidBepalingsprocedure

## Beschrijving
"monster te troebel " wordt in de codelijst gemist. Het beste monster wordt verkregen als het watermonster dezelfde helderheid heeft als het water zoals dat door natuurlijke krachten door de formatie beweegt. Dit zal veelal het geval zijn wanneer de troebelheid 10 NTU (Nephelometric Turbidity Unit) of lager is. Ook wanneer een hogere troebelheid dan  10 NTU wordt geconstateerd, kan toch monsterneming plaatsvinden (dit geldt niet als een afwijking). Pas met de interpretatie van de analyseresultaten zal worden beoordeeld of troebelheid een probleem vormt. Zie bijlage C NEN 5744 voor meer uitleg hierover.

## Oplossingsrichting
Opnemen van "monster te troebel" in de codelijst

**Comment by AnnitaVijverberg** [comment]
We hebben besloten de bijzonderheden bepalingsprocedure niet meer op te nemen. Dit is een gegeven dat op dit moment niet wordt uitgewisseld. Er worden alleen, soms, opmerkingen (vrije tekst) op het analyse certificaat vermeld. Zie ook issue #66.
De troebelheid wordt wel als veldmeting en/of als analyseresultaat opgeslagen
