### ISSUE TITLE
Aquo-code of CAS-nummer als sleutel

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GAR#42]
We maken gebruik van een referentielijst om diverse gegevens van een stof vast te leggen: CAS-nummer, Aquo-code, parameternaam, definitie, eenheid. De bronhouder hoeft slecht één gegeven aan te leveren, de rest volgt uit de referentielijst. Het ene aan te leveren gegeven is de sleutel tussen de meetwaarde en de gegevens over de stof.

Welk gegeven kunnen we het beste als sleutel gebruiken?
Het beste kan een code als sleutel worden gebruikt. Bij teksten (naam) is er namelijk snel een verschil in schrijfwijze of een schrijffout gemaakt. Dan is er de keuze tussen het CAS-nummer en de Aquo-code.
_CAS-nummer_ wordt internationaal zeer veel gebruikt, nadeel is dat er geen CAS-nummer is voor stofgroeperingen zoals 'totaal stikstof' of 'totaal fosfor' of voor groepen isomeren. Ook niet voor zaken als troebelheid en geleidbaarheid
_Aquo-code_ is er ook voor troebelheid etc. en voor groepen van stoffen (Ptot etc). Nadeel is dat Aquo-code veel minder breed gebruikt wordt. Waterbedrijven gebruiken deze codering bijvoorbeeld niet (in elk geval niet alle waterbedrijven).

**Comment by AnnitaVijverberg** [comment]
Uit het gesprek Met Janco van Gelderen: Het is waarschijnlijk verstandig om naast de Aquo-code ook het CAS-nummer op te geven om er zeker van te zijn dat we het over dezelfde stof hebben. Aquo wordt door Waterschappen (voor oppervlaktewater), IHW en de provincies gebruikt. Niet helemaal zeker of het RIVM deze codes ook gebruikt (vragen we na).

Aquo beschrijft ook in welke eenheid een stof aangeleverd moet worden. In de BRO willen we dat op een wat andere manier doen. 

Om meer te weten te komen over het beheer en de toegankelijkheid van Aquo kunnen we het beste met de beheerders van IHW een afspraak maken.

**Comment by AnnitaVijverberg** [comment]
Het Waterlaboratoruim (HWL) werkt niet Aquo codes en is het bij haar klanten ook nooit tegengekomen:
[Materiedeskundige van HWL] "Wij hebben in ons LIMS systeem de CAS-nummers en Kiwa codes opgenomen. Mocht er een ander code bij moeten komen zou dat betekenen dat er in ons LIMS een extra veld aangemaakt moet worden. Dat is lastig maar niet complex. Ik zie geen problemen om meerder codes te moeten hanteren."

**Comment by JancovanGelderen** [comment]
@ Anita: Aquo beschrijft ook in welke eenheid een stof aangeleverd moet worden. In de BRO willen we dat op een wat andere manier doen.
Wat willen jullie dan in de BRO anders gaan doen?

**Comment by lvdbrink** [comment]
Uit sprintreview 25 okt verslag: 

> Opmerkingen over aquo-code/CAS-nummer
> Janco: De aquostandaard beschrijft naast de code ook de eenheid. Deze horen bij elkaar. Verder beschrijft Aquo of er gefiltreerd moet worden en in welke hoedanigheid gemeten moet worden. Bijvoorbeeld fosfaat in P (ipv in PO4). Janco adviseert om Aquo dan in zijn geheel te gebruiken dus ook de eenheid, bewerking en hoedanigheid.
> Anders is het verwarrend.
> Nadeel is dat lang niet iedereen in het werkveld deze standaard gebruikt.
> 
> Frank licht de juridische kant toe van codelijsten: Deze staan volledig in de ministeriële regeling, een verwijzing naar de meest recente Aquo-lijst kan juridisch niet. Dat betekent maximaal één update per jaar. Beheer hierop moet nog worden vormgegeven. Moet werkbaar zijn, maar ook juridisch op de juiste manier. Bijvoorbeeld dmv werkafspraken.
> Actie: Frank neemt op zich om de beheerprocedure af te spreken voor codelijsten.

**Comment by lvdbrink** [comment]
Het zou ook een optie kunnen zijn om simpelweg de URL van een aquo code op te nemen. 

Bijvoorbeeld 
`http://standaard.aquo.nl/id/begrip/33782`

**Comment by JancovanGelderen** [comment]
Hoi Linda,

Ik denk inderdaad dat het goed is om een link naar Aquo op te nemen.

Er is daarbinnen een ‘stofcodelijst grondwater’ beschikbaar maar deze is vermoedelijk niet compleet omdat er toch veelal stoffen bijkomen.
De aquoparameterlijst is wel altijd zo actueel mogelijk.

De aquostandaard is aangemeld op de ‘pas toe of leg uit lijst’ en is daarom zeer sterk aan te bevelen.
Alle provincie gegevens zullen daar aan voldoen, als straks waterbedrijven moeten inleveren aan de BRO onder de  vergunning van de bronhouder provincie dan zullen provincies ook die uitleverstandaard voorschrijven.

De aquostandaard is juist ook bedoeld en opgezet om zo min mogelijk interpretatieverschillen te krijgen over de meetgegevens.

**Comment by JancovanGelderen** [comment]
Nb. In aanvulling die lijst word continu geactualiseerd dus in de BRO kan dan worden opgenomen dat deze lijst continue wordt aangevuld. De BRO kan dat dan bijvoorbeeld jaarlijks updaten.

De meeste bronhouders zullen data ook slechts jaarlijks uitleveren.

**Comment by AnnitaVijverberg** [comment]
Input HWL over de hoedanigheid die ook door Aquo wordt voorgeschreven:
Het analyse apparaat geeft bijv. mg P/l, maar soms ook beide: zowel mg P/l als mg PO4/l. Daarnaast kan het makkelijk omgerekend worden, vaak wordt dit door software gedaan. Als het niet al wordt gedaan kan het redelijk makkelijk geïmplementeerd worden.

**Comment by AnnitaVijverberg** [comment]
De juristen van het ministerie hebben aangegeven dat lijst met parameters opgenomen moet worden in de catalogus. We kunnen dus niet volstaan met een link.
We stellen een referentielijst samen met daarin naast de Aquo-code (dit is de sleutel), het CASnummer, omschrijving, eenheid en hoedanigheid. De lijst heeft als basis de Aquo parameterlijst Grondwaterkwaliteit - IHW, aangevuld met parameters van de Aquo parameterlijst Bodemkwaliteit – compartiment Grondwater - SIKB en aangevuld met de bij ons bekende prameters waar grondwater verder op bemonsterd wordt. 
Deze lijst zal in de beheerfase steeds geupdate moeten worden ivm nieuw gemeten stoffen. Deze referentielijst zal in XML formaat beschikbaar komen zodat ook de stakeholder die nog geen gebruik maken van Aquo deze eenvoudig kunnen gaan hanteren.
We gebruiken de Aquo-code als sleutel omdat de Aquo-code er ook is voor troebelheid, pH, temperatuur etc. en voor groepen van stoffen (Ptot, sommaties van isomeren etc).

**Comment by rbv305** [comment]
ok

**Comment by KoosBoersma** [comment]
Vraagje, Ontdanks dat de call gesloten is. Hoe is de onderlingen afstemming tussen de verschillende standaarden geregeld?? Governance !

**Comment by rbv305** [comment]
Daar is eigenlijk het informatiehuis water voor ingericht.

**Comment by KoosBoersma** [comment]
Klopt en deze rol willen we ook graag gaan vervullen. Echter dat begint wel met onderlinge afstemming en overleg.  PS. werkzaam bij het IHW

**Comment by RLHuisman** [comment]
In de huidige versie staat ID : Nummer (id) als key, dit is neem ik aan het SIKB ID?

**Comment by AnnitaVijverberg** [comment]
> In de huidige versie staat ID : Nummer (id) als key, dit is neem ik aan het SIKB ID?

Dat klopt Robin
