### ISSUE TITLE
Welke data (datums) leggen we vast in de BRO?

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GAR#43]
Er zijn een aantal verschillende data (datums) die in de BRO vastgelegd (kunnen) worden:
- Datum veldonderzoek (De datum waarop het veldonderzoek is uitgevoerd.)
- Rapportagedatum veldonderzoek (De datum waarop het resultaat van het veldonderzoek aan de opdrachtgever is gerapporteerd.) 
- Datum(s) labonderzoek (de datum waarop de labanalyse is uitgevoerd. Labanalyses worden waarschijnlijk niet allemaal op dezelfde dag uitgevoerd)
- Rapportagedatum labonderzoek (De datum waarop het complete resultaat van het labonderzoek is gerapporteerd aan de bronhouder.)
- Daarnaast is er de registratiegeschiedenis van het grondwatersamenstellingsonderzoek (datum van aanbieden aan de BRO en data van eventuele correcties).
Welke is van belang om vast te leggen?

Janco van Gelderen geeft aan dat (uit gesprek op 4 oktober 2018) de rapportagedatum veldonderzoek voor hem niet van belang is. Bemonsteringsdatum veld wel. Bij lab is voor Janco ook de analysedatum interessant. Als je die van veld en lab vergelijkt zie je of de conserveringstermijn niet wordt overschreden. Bij lab wordt niet alles op dezelfde dag uitgevoerd. Labs geven per gemeten stof een analysedatum op. De opleverdatum van het lab is wanneer zij de pdf met resultaten opleveren. Naast de pdf wordt er door de labs een Excel opgeleverd maar meestal niet op dezelfde dag.

Het BRO standaardisatieteam is van mening dat overschrijding van de conserveringstermijn bij uitstek in de labels aangegeven kan worden (was aanvankelijk gemodelleerd in de bijzonderheden/afwijkingen Labprocedure). Conserveringstermijn verschilt mogelijk in de tijd, per lab, per methode, per stof en is daardoor niet zomaar uit het verschil tussen 2 data af te lezen. De datum van het labonderzoek per stof gaan we alleen gaan vastleggen als dat gegeven op zichzelf waardevol is.

**Comment by AnnitaVijverberg** [comment]
[Materiedeskundige van Het Waterlaboratoruim (HWL)] "Bij HWL hebben we datum monsterneming wat tevens de datum is van veldwerk c.q. veldonderzoek. Deze datum is in de communicatie daarna bepalend (unieke monsterpunt code en datum en eigenlijk hoort daar ook tijdstip monsterneming bij omdat er soms meerdere monsters per dag op het zelfde monsterpunt genomen moet worden). Daarnaast heb je nog allerlei andere data. Bijvoorbeeld datum analyse, i.v.m. houdbaarheid (conserveringstermijn), datum rapportage, i.v.m. doorlooptijd, en datum facturering als alle analyses uitgevoerd en geautoriseerd zijn en dus compleet is."

De conserveringstermijn is afhankelijk van de methode.
Het komt niet vaak voor maar een enkele keer wordt op dezelfde dag een put 2 keer bemonsterd.
Doorlooptijd is voor klanten van HWL (opdrachtgevers: waterbedrijven) belangrijk, de minimum doorloopt tijd wordt vaak afgesproken tussen opdrachtgever en -nemer.

**Comment by JancovanGelderen** [comment]
@Annita in aanvulling voor provincies is alleen datum bemonstering (veldwerk) en datum analyse relevant. Het gegeven wat het HWL aangeeft van meerdere monsters per dag is voor de provinciale meetnetten zeer onwaarschijnlijk. Rapportagedatum voor zowel veld als lab is voor de provincies niet relevant want daar doe je verder niks mee. Overschrijding van de Conserveringstermijn wordt door het het lab wel aangegeven op de analysestaat (PDF) maar niet in het Excel overzicht. Realiseer ook dat dit weer een extra veld is aangezien dit per parameter aangegeven moet worden. Dit zou op dit moment een handmatige exercitie worden om dat aan te vullen. Voor de toekomst zal dan het uitleverformat van de labs moeten worden aangepast indien je dit wel wil opnemen. Bij onze validatie heb ik niet eerder meegemaakt dat om de reden van overschrijden conserveringstermijn gegevens zijn afgekeurd.

**Comment by AnnitaVijverberg** [comment]
We concluderen dat in elk geval datum veldonderzoek en datum labonderzoek gewenst is door de provincies. We kijken verder naar datum labonderzoek op het moment dat we meetmethoden en normen oppakken.

**Comment by lvdbrink** [comment]
> We kijken verder naar datum labonderzoek op het moment dat we meetmethoden en normen oppakken.

Hier wordt denk ik **rapportagedatum** lab bedoeld?

**Comment by AnnitaVijverberg** [comment]
Uit onze analyse hebben we het volgende geconcludeerd dat we 2 data wel en 2 data niet opnemen (naast de automatisch gegenereerde datum (tijdstip) van registratie in de BRO)
Data die we wel opnemen:
•	‘datum veldonderzoek’ – dit is de start van de analyse, van een GAR, de datum waarop de grondwatermonsters zijn genomen. De datum (jaargetijde) kan van invloed zijn op sommige meetwaarden.
•	‘datum lab-analyse’ – dit is de datum waarop de analyse in het lab is uitgevoerd. Deze datum wordt per onderzoeksproces vastgelegd omdat niet alle analyses altijd op dezelfde dag worden uitgevoerd. Deze datum is interessant i.v.m. de conserveringstermijn van de grondwatermonsters en interessant omdat deze datum de start aangeeft van het verzamelen van de meetwaarden van de parameters gemeten in het lab.
Data die we niet opnemen:
•	‘rapportagedatum veldonderzoek’ – Dit is de datum waarop de uitvoerder van het veldonderzoek de resultaten van de veldmetingen rapporteert aan de bronhouder. Dit is de doorlooptijd van het veldonderzoek en is niet van belang. De bronhouder spreekt met de uitvoerder een maximale doorlooptijd af. 
De datum waarop het totale onderzoek (het GAR) in de BRO is opgenomen wordt vastgelegd in de registratiegeschiedenis. De tijd tussen ‘datum veldonderzoek’ en ’tijdstip registratie object’ is de totale doorlooptijd. Het is niet zo interessant te weten welk deel van deze doorlooptijd in beslag is genomen door de uitvoerder van het veldonderzoek.
•	‘rapportagedatum labonderzoek’ - Dit is de datum waarop de uitvoerder van het labonderzoek de resultaten rapporteert aan de bronhouder. Dit is de doorlooptijd van het labonderzoek en is niet van belang. De bronhouder spreekt met de uitvoerder een maximale doorlooptijd af. Net als bij de rapportagedatum veldonderzoek,  is het ook hier niet zo interessant te weten welk deel van de totale doorlooptijd door de doorlooptijd van het labonderzoek in beslag wordt genomen.

**Comment by AnnitaVijverberg** [comment]
Bovenstaande is gepresenteerd tijdens de sprintreview van 20-12-2018 en akkoord bevonden.
