### ISSUE TITLE
Geen inhoudsopgave in ReSpec door lege elementen in titels van GAR-cat.html

### ISSUE THREAD

**Issue by thijsbrentjens** [BROprogramma/GAR#44]
Bij het updaten van ReSpec liepen we er tegenaan dat er geen inhoudsopgave (TOC) gemaakt werd voor https://broprogramma.github.io/GAR/. Het blijkt te maken te hebben met lege anchor elementen in sommige titels van [GAR/data/GAR-cat.html](GAR/data/GAR-cat.html). 
In de HTML zijn die te vinden als:

```
<a href="#"></a>
```
Deze elementen lijken niet nodig. Kunnen ze verwijderd worden?

Zie ook https://github.com/Geonovum/respec/issues/152#issuecomment-428551228

ReSpec gaat er trouwens in het vervolg rekening mee houden, maar toch lijkt het me goed de elementen te verwijderen.

**Comment by lvdbrink** [comment]
GAR-cat.html wordt gegenereerd door Imvertor. Ik heb het probleem met de lege anchors daar aangemeld.

**Comment by AnnitaVijverberg** [comment]
We ervaren op dit moment geen probleem bij het genereren van de catalogus. We sluiten daarom dit issue.
