### ISSUE TITLE
Fysische parameters lab/veld

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GAR#46]
Uit de sprintreview van 25 oktober 2018 kwam naar voren dat er nog een aantal toestandsparameters zijn die in het lab worden gemeten die mogelijk vastgelegd moeten worden zoals: geur, kleur, dichtheid (zoet/zout)

**Comment by AnnitaVijverberg** [comment]
Input van Het Water Laboratorium:
Het HWL bemonsterd drinkwater op geur, kleur en ook smaak (chemisch en met een pannel). Voor Grondwater gebeurt het veel minder of niet bij HWL. In het veld gebeurt dit wel visueel: beoordeling op kleur.
In het lab zou geur (houdt verband met zuurstofgehalte) en kleur eventueel waardevol kunnen zijn. WHL ziet geen waarde in de dichtheid.

**Comment by AnnitaVijverberg** [comment]
Input OMWB:
Wat wij hier Fysische parameters noemen, worden bij OMWB veldparameters genoemd. OWMB is van mening dat die parameters in het veld bepaald moeten worden en niet op het laboratorium.
In de tijd tussen de veldmeting en de uiteindelijke labmeting gebeuren er diverse zaken die de waarde van deze parameters beïnvloeden. Ook kunnen er in de fles processen plaatsvinden.

**Comment by AnnitaVijverberg** [comment]
Is bij de parameters die we onder deze groep scharen het analyseproces van belang om vast te leggen? Zijn er verschillende technieken om deze parameters te bepalen? Zo ja, bepaalt de gebruikte techniek de waarde of nauwkeurigheid van de meting? M.a.w. heeft het vastleggen van de analysetechniek hergebruikswaarde voor gebruikers?

**Comment by AnnitaVijverberg** [comment]
Er is geen ondersteuning gevonden voor het toevoegen van aanvullende parameters bij de nu genoemde fysische (toestands)parameters die in het lab worden gemeten. Actie uit de sprintreview van 20-12-2018: stakeholders die van mening zijn dat er aanvullende ‘toestandsparameters’ opgenomen moeten worden melden zich vóór 19 januari bij het BRO standaardisatieteam.

Aanvullend overwegen we:
- Kleur en evt geur toe te voegen aan de veldwaarnemingen
- Geen onderscheid meer te maken in fysische (toestands)paramters en chemische parameters maar ze in het model samen tevoegen. Dan wordt ook bij de toestandsparameters het analyseproces vastgelegd.

**Comment by AnnitaVijverberg** [comment]
- In bepaalde gevallen mag een grondwatermonster juist niet op geur bemonsterd worden, daarom nemen we geur niet op.
- Kleur hebben opgenomen als item op de codelijst bijzonderheden veldonderzoek: Afwijkende kleur: Het grondwater is niet doorzichtig, maar heeft bijvoorbeeld een roestige of venige kleur. Hierdoor kan gedurende de dag een filmlaag op de elektrodes in de meetapparatuur neerslaan. Dit kan de meting van de geleidendheid (EGV/EC) en de pH beïnvloeden.
- Veld- en labparameters hebben we op dezelfde manier gemodelleerd namelijk zonder onderscheid in type parameter en door gebruik te maken van een prameter-referentielijst.

**Comment by rbv305** [comment]
Begrijp ik nu goed dat er voor type parameter  nu geen onderscheid meer is tussen zuurstof, pH en EGV gemeten in het veld en het lab ? Maar dat het verschil moet worden afgeleid uit het analyseproces ?

**Comment by AnnitaVijverberg** [comment]
Nee, dat is niet juist. Zowel bij Resultaat veldmeting als bij Resultaat parameters (de labmetingen). Kan gekozen worden uit een hele lijst parameter (een referentielijst). Op die lijst staan ook pH, EGV, zuurstof etc. Wat hierboven bedoelt wordt is dat er alleen nog onderscheid is gemaakt tussen de veldmetingen en de labmetingen maar dat binnen de veld- en de labmetingen geen verdere onderverdeling meer is gemaakt (naar bijvoorbeeld chemische parameters en fysische parameters).

**Comment by rbv305** [comment]
Ok dus zuurstof gemeten in het veld krijgt een andere parametercode dan zuurstof gemeten in het lab ?

**Comment by AnnitaVijverberg** [comment]
Zuurstof wordt in de parameterlijst geïdentificeerd met aquocode: O2. zowel het resultaat van de labmetingen als de veldmetingen maken gebruik van dezelfde parameterlijst. Zuurstof kan, geïdentificeerd als O2, drie keer opgeslagen worden: bij reslutaat veldmeting met in situ: ja, bij resultaat veldmeting met in situ: nee en bij reslutaat labmeting. Is dit een antwoord op je vraag Sander?

**Comment by rbv305** [comment]
Ja het is mij helder nu

**Comment by AnnitaVijverberg** [comment]
Tijdens de sprintreview van 14 februari ontstond een discussie over in situ. Deze discussie is verder per email met een selecte groep mensen uitgediept. Zie hieronder:

 [Annita] Ik zet de gedachtewisseling over in/ex situ graag per email op. 

Een aantal zaken vooraf:
- De resultaten van veld- en labmetingen zijn gesplitst in het gegevensmodel.
- Van de veldmetingen worden deels andere attributen opgeslagen dan van de labmetingen. Hieronder wat wordt vastgelegd bij Resultaat veldmetingen:
   - parameter
   - waarde
   - in situ
   - status kwaliteitscontrole

in situ ja/nee, is een attribuut dat alleen bij de veldmetingen wordt opgeslagen. De definitie is: " De aanduiding die aangeeft of de parameter in het grondwater in de put bepaald is, dan wel in het opgepompte grondwater."

We hebben ons 2 dingen afgevraagd:
1) Wordt er zowel in situ als ex situ gemeten en 2) is het relevant het verschil vast te leggen?

Een veldwerker het RIVM gaf in januari van dit jaar aan:
"De temperatuur in de doorstroomcel kan flink afwijken van de watertemperatuur in de put. Wij meten deze allebei. De watertemperatuur in de doorstroomcel is wel belangrijk omdat deze wat zegt over de Ec waarde, welke ook in de doorstroomcel wordt gemeten. De gemeten waarde in de doorstroomcel zal zeker bij extreme buitentemperaturen enkele graden afwijken van de grondwatertemperatuur."
Ook in maart 2018 hebben we opgetekend dat het RIVM de temperatuur maar ook zuurstof in situ meet. Met in situ wordt hier onderin de pijlbuis, in het grondwater bedoeld.

TNO geeft aan dat bij warm weer de temperatuur in het opgepompte water behoorlijk kan afwijken van de grondwatertemperatuur onderin de put.

Onze conclusie is dat er vooral ex situ wordt gemeten maar dat in situ ook voorkomt en het verschil kan relevant zijn, met name bij temperatuur is dat het geval.

Ik hoor graag als jullie het met deze conclusie niet eens zijn en waarom.

Ik begrijp dat de terminologie voor provincies verwarrend is omdat zij op dit moment de term in situ gebruiken voor veldmetingen en ex situ voor labmetingen. Klopt toch Janco?
Kunnen we eventueel een andere term hanteren die de lading ook dekt en minder verwarring veroorzaakt? Hebben jullie suggesties?

[Karel] De meting behoort bij een meetpunt met filterdiepte (zeg 9-10m-mv).    De waarden die dan gerapporteerd worden hebben betrekking op de diepte van 9-10m. Zo worden die data ook gepresenteerd en verder gebruikt in het vervolgproces. 
Wanneer de meting in een doorstroomcel gedaan wordt en afwijkt is dat dus niet representatief voor die diepte en niet de juiste manier van meten.   Dan moet je dus alleen beneden in het filter meten (in de bemonsteringsnorm-procedure vastleggen).  Temp en ec , ph e.d. hebben een relatie met elkaar. Wanneer je dan goed wilt meten moet je dat onderin meten en niet meer in een doorstroom cel. 
Een doorstroomcel mag je alleen gebruiken voor metingen die daar niet gevoelig voor zijn.

[Janco] Ik begrijp dat veld en lab dus al sowieso uit elkaar is gehaald in het model dat is mooi.
Het verschil binnen veldmetingeb met in de buis of in de doorstroomcel is dan een tweede.
Wat mij betreft vervangen we dan de term in situ/ ex situ in: meting onderin peilbuis / meting in doorstroomcel dan is dat maar duidelijk. 

[Mariëlle] Het voorstel van Janco ‘onderin peilbuis’ en ‘meting in doorstroomcel’ vind ik ook duidelijk.
In-situ betekent letterlijk ‘op zijn plaats’, daarmee wordt wat mij betreft in de peilbuis bedoelt. Maar als hier eerder ook het verschil tussen lab en veld (doorstroomcel in het veld) mee is bedoelt, lijkt het me goed om het voorstel van Janco over te nemen.

[Annita] Bedankt voor jullie reacties. Het attribuut waar we het hier over hebben is een indicatie ja/nee attribuut. Nu heet het attribuut 'in situ' en kan ja of nee (of onbekend in het geval van IMBRO/A) ingevoerd worden.
We kunnen dit aanpassen en moeten dan een keuze maken tussen ofwel 'onderin peilbuis' (mogelijkheid ja/nee/onbekend) ofwel naar 'in doorstroomcel' (mogelijkheid ja/nee/onbekend).
We moeten dus een keuze in maken.
Ik zie een paar voors en tegens voor beide termen:

Voor 'in doorstroomcel'
- in de meeste gevallen  is hier 'ja' van toepassing, daardoor duidelijk
Tegen 'in doorstroomcel'
- heeft met de techniek te maken. Als in de toekomst een andere techniek gebruikt kan worden (hoe waarschijnlijk?) klopt de term niet meer en moet aangepast worden

Voor 'onderin peilbuis'
- duidelijke term
Tegen 'onderin peilbuis'
- in de meeste gevallen beantwoord met 'nee' waardoor deze term minder voor de hand ligt.

Hebben jullie een voorkeur en zo ja welke en waarom?

[Janco] Ik denk dat je nieuwe voorstel goed is. Er is nog weinig anders te verwachten op dit vlak.
Sowieso zijn de metingen in doorstroomcel onderdeel van de werkwijze van de provincies in NTA8017.
Mijn voorstel is dat er een keuze kan worden gemaakt uit: of doorstroomcel of onderin peilbuis
Dan hoef je geen ja nee in te vullen.
Je vult dit tenslotte alleen in als er ook een waarde voor een parameter wordt gerapporteerd.
Is dat niet meest eenvoudige oplossing?
Dan heet veld 'plaatsbepaling veldmeting' Ofzo. 

[Mariëlle] Ik ben het eens met Janco: kies voor doorstroomcel of onderin peilbuis.
Stel je hebt alleen de keuze uit doorstroomcel  ja of nee. Bij nee weet ik dan nog steeds niet of het bijvoorbeeld in een monsterflesje is gemeten of op filterdiepte.
Onderin peilbuis is eigenlijk niet helemaal de juiste term. Eventueel is deze term te vervangen door ‘op filterdiepte’.

**Comment by AnnitaVijverberg** [comment]
Bedankt voor het meedenken!
We hebben de volgende aanpassingen gedaan:
In plaats van 'in situ ja/nee' hebben we nu het attribuut 'plaats veldmeting'.
Bij dit attribuut hoort een codelijst waar nu de items aanhangen:
- in doorstroomcel
- op filterdiepte
- onbekend (alleen voor IMBRO/A, historische data)
Stel dat er in de toekomst andere technieken komen kunnen die toegevoegd worden aan de codelijst.

Hiermee kan het issue worden gesloten
