### ISSUE TITLE
bemonstering

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GAR#47]
anoxie of hypoxie; In grondwater is de zuurstofconcentratie nihil. Het water is niet in evenwicht met de atmosfeer. Oxidatieprocessen worden daardoor sterk belemmerd. Zonder maatregelen zal bij de bemonstering het grondwater belucht worden, zeker als daar een pomp bij gebruikt die lucht aanzuigt.

Nu wordt voorzien in het opslaan van enkel pomptype en slangtype. Gezien bovenstaande moet in overweging genomen worden of er meer gegevens (bijv. pompsnelheid) vastgelegd moeten worden.

**Comment by AnnitaVijverberg** [comment]
We hebben nu nog in het gegevensmodel het attribuut bijzonderheden vedonderzoek staan met de onderstaande mogelijkheden:
monsterBelucht
filterBelucht
EGVMoeilijkTeBepalen
teveelDalingGrondwaterstand
afwijkendFilter
afwijkendGekoeld
afwijkingInMeetapparatuur
contaminatieDoorVerbrandingsmotor
Een aantal van deze bijzonderheden hebben met beluchting te maken. Tijdens de sprintreview van 25 oktober is besloten: "We wachten de uitkomst van het labels-onderzoek  af, daarna besluiten we over bijzonderheden veldonderzoek.

**Comment by AnnitaVijverberg** [comment]
De bijzonderheden veldonderzoek geven bijzonderheden aan die in het veld optraden en/of afwijkingen van de gehanteerde bemonsteringsprocedure. Dit kan maar hoeft geen gevolgen te hebben voor de status kwaliteitscontrole. Deze bijzonderheden worden genoteerd door het veldbureau en geven extra informatie aan de gebruiker en worden daarom opgeslagen in de BRO.
Naar onze mening zijn nu voldoende items op de codelijst aanwezig voor het aangeven van mogelijke beluchting van het grondwater.
