### ISSUE TITLE
Accreditatie door Raad voor Accreditatie (RvA) 3.3

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GAR#48]
Geaccrediteerde laboratoria hebben een lijst met analyses die geaccrediteerd zijn. De actuele scope is openbaar (www.RvA.nl) maar wel tijdgebonden, er kunnen in de tijd  wijzigingen in aangebracht zijn. Of een meetresultaat onder accreditatie is uitgevoerd is dus soms lastig te achterhalen aangezien er voorzover ik weet bij de RvA geen historie van de scope beschikbaar is.

**Comment by AnnitaVijverberg** [comment]
Zie ook issue nr 9. We hebben de bepalingstechniek en de bepalingsprocedure (de norm/het voorschrift) opgenomen in het gegevensmodel.  Een meting van een stof waar een lab een accreditatie voor heeft (de stof is volgens een bepaalde NEN norm uitgevoerd), kan toch zonder Q zijn. Dit gebeurt als bijvoorbeeld de conserveringstermijn is overschreden. Dat kan een QClabel zijn dat tot een bepaalde QCstatus leidt. In het rapport Categorieën datakwaliteit is opgenomen dat de QClabels nog uitegewerkt moeten worden. Kan dit een punt zijn dat daarin wordt meegenomen?

**Comment by harryvanmanen** [comment]
Begrijp ik het goed:
-dat, voor zover mogelijk, de bepalingstechniek en de bepalingsprocedure wordt opgenomen. 
-Voor analyses waarbij deze informatie ontbreekt/niet mogelijk is, dit kan dat worden geduid middels het QClabel.

**Comment by AnnitaVijverberg** [comment]
We hebben nu inderdaad bepalingstechniek en -procedure opgenomen.
Bij je tweede bullet: ontbreekt deze informatie bij historische data of ook bij data die nu ingewonnen wordt? Kan een laboratorium daar niet altijd duidelijkheid over geven?
Of een meting met of zonder Q is gedaan zegt iets over de kwaliteit, betrouwbaarheid van de meting en zou je daarom in een QClabel kunnen vatten maar zover gaat het net opgeleverde rapport nog niet.

**Comment by harryvanmanen** [comment]
Hallo Anita,

Naar aanleiding van het vorige overleg wil ik nog een aantal GAR bemonsteringsprocedures aanleveren voor opname in de codelijst:
-         BRL SIKB 2000 – protocol 2002 Het nemen van grondwatermonsters;
-         NEN 5706 Richtlijnen voor de beschrijving van zintuiglijke waarnemingen tijdens de uitvoering van milieukundig bodemonderzoek;
-         NEN 5861 Procedures voor de monsteroverdracht;
-         NEN-EN-ISO 5667-3 Monsterneming - Deel 3: Richtlijn voor de conservering en behandeling van watermonsters;

Groeten,
Harry van Manen
[email footer verwijderd]

**Comment by AnnitaVijverberg** [comment]
De eerste (SIKB protocol 2002) hebben we opgenomen in de codelijst van bemonsteringsprocedure.
De tweede (NEN 5706) gaat over milieukundig bodemonderzoek. Dat is buiten scope. Daarnaast zijn zintuigelijke waarnemingen niet opgenomen in het gegevensmodel.
De monsteroverdracht (NEN5861) is ook niet opgenomen in het gegevensmodel. Daarom hebben we deze norm ook niet opgenomen.
Ook conservering en behandeling (NEN-EN-ISO 5667-3) is niet afzonderlijk opgenomen in het gegevensmodel. 
Daarnaast wordt in de nu opgenomen procedures (NTA8017, NEN5744 en Protocol2002) verwezen naar de tweede , derde en vierde norm uit de lijst van Harry.

Met deze aanpassing kan dit issue worden gesloten.
