### ISSUE TITLE
Meetonzekerheid 3.3.1

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GAR#49]
De laboratoriumpraktijk van NL hanteert wel de termen Aantoonbaarheidsgrens (AG) en Rapportagegrens (RG), maar niet meer de Bepaalbaarheidsgrens of Bepalingsgrens (BG).

Wat hier ontbreekt is de meetonzekerheid. Dat is een belangrijke parameter om het resultaat te kunnen interpreteren en zou zeker opgenomen moeten worden indien beschikbaar. 
Er wordt in paragraaf 2.8 wel iets over gezegd maar dat is wel heel vrijblijvend. Het werkt eigen interpretatie achteraf in de hand.
Geaccrediteerde laboratoria zijn verplicht informatie over de meetonzekerheid te verschaffen. Dat kan direct vastgelegd worden.
Bij voorkeur zijn bij de bepaling van de meetonzekerheid zowel bronnen van onzekerheid die voortvloeien uit de bemonstering als uit de analytisch bewerking op het lab.
In het ideale geval wordt bij het rapporteren van resultaten gebruik gemaakt van de samenstelling mr ± u (mr = meetresultaat; u is onzekerheid).
Een resultaat onder de RG niet hoeft dan feitelijk niet als uitkomst  <RG  te hebben.
Voordeel is ook dat het aantal significante cijfers niet van belang is.

Voorbeeld
[Cl] = 233,15 ± 10,22 mg/L
Als RG = 300 dan zou dit nu vertaald worden als <300 mg/L
Als RG = 100 dan zou dit nu vertaald moeten worden als 230 mg/L
In beide gevallen is er informatie verdwenen. 

Bijzonderheden bij de bemonstering en/of analyse worden vastgelegd. Vraag is of daar iets van door zou moeten sijpelen naar BRO. Je kunt denken aan bepaalde kwaliteitscodes.

**Comment by AnnitaVijverberg** [comment]
We hebben afgewogen of de meetonzekerheid opgenomen moet worden en besloten dat niet te doen. De reden is dat er een aantal andere attributen zijn opgenomen die ook iets zeggen over de betrouwbaarheid namelijk de techniek waarmee is gemeten en de procedure (NEN norm bijv) die is gehanteerd bij het meten. Daarnaast zou het toevoegen van de meetonzekerheid een detailniveau toevoegen aan het gegevensmodel dat verder in het model niet is opgenomen. 

We zijn wel benieuwd of er mensen zijn die veel belang hechten aan het opnemen van meetonzekeheid

**Comment by rbv305** [comment]
Een meetonzekerheid kan zeker waardevol zijn bij de inepretatie van meetresultaten. Als de informatie er is kan het wat mij betreft opgenomen worden.

**Comment by rbv305** [comment]
Informatie over meetonzekerheid kan zeker van waarde zijn bij het interpreteren van de meetresultaten. Als de informatie voorhanden is kan het wat mij betreft worden opgenomen. Ik ben het overigens nog nooit tegengekomen bij mijn analyseresultaten.

**Comment by JvVelthuijsen** [comment]
Binnen het werkveld bodem (grond en grondwater) worden de gehalten op het analysecertificaat als waar/de juiste waarde beschouwd. Bij een interpretatie moet je wel in gedachten houden dat het getal een bepaalde meetonzekerheid heeft. Voor zover bij mij bekend kan alleen bij de grondwatermonitoring bij RWZI's rekening gehouden met de meetonzekerheid van het lab (hiervoor is een handreiking opgesteld, maar deze heeft geen formele status; wordt in PNB wel toegepast). Binnen het werkveld geluid en lucht wordt wel rekening gehouden met meetonzekerheden in de verkregen getallen. Mbt de BRO, graag géén meetonzekerheden inbouwen, daarmee zet je de 'hele bodemwereld' op zijn/haar kop!!

**Comment by AnnitaVijverberg** [comment]
We nemen het nu (voor de publiek consultatie) niet op en wachten eventuele reacties tijdens de publieke consultatie af.

**Comment by harryvanmanen** [comment]
Okay.

Groeten,

Harry van Manen
Rijkswaterstaat WVL
T 06 13 70 42 69

Van: AnnitaVijverberg [mailto:notifications@github.com]
Verzonden: donderdag 14 maart 2019 9:14
Aan: BROprogramma/GAR
CC: Manen, Harry van (WVL); Author
Onderwerp: Re: [BROprogramma/GAR] Meetonzekerheid 3.3.1 (#49)


We nemen het nu (voor de publiek consultatie) niet op en wachten eventuele reacties tijdens de publieke consultatie af.
