### ISSUE TITLE
Meten van Cl gehalte in het veld

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#5]
De typering van het grondwater (zoet/zout) is in het huidige model opgenomen bij het Grondwatersamenstellingsonderzoek. Het chloridegehalte wordt echter in de huidige praktijk niet standaard in het veld bepaald. Als indicatie voor Cl kan kan ook geleidbaarheid (Ec) genomen worden. Het meten van Cl in het veld is echter geen ingewikkelde bepaling en heeft voor labs toegevoegde waarde. Het kan een overweging zijn om te kijken of een bepaling voor Cl voor ‘BRO-onderzoeken’ onderdeel kan worden van de gebruikte bemonsteringsnorm.

**Comment by lvdbrink** [comment]
Chloride in het veld meten lijkt op basis van gesprek met veldwerk experts geen goed idee; laboratoria kunnen de informatie die ze nodig hebben afleiden uit de EC meting.

**Comment by lvdbrink** [comment]
We willen dit een discussiepunt laten zijn met een bredere vertegenwoordiging van het veldwerk.

**Comment by lvdbrink** [comment]
Marielle van Vliet (TNO): 

> Ik vind dat typering van het grondwater d.m.v. Cl hier niet thuis hoort. En het uitbreiden van de bemonsteringsnorm met Cl alleen voor dit attribuut vind ik heel ver gaan en is de omgedraaide wereld!!  Aangezien klasse (zoet, brak of zout) bijna niet verandert.

**Comment by AnnitaVijverberg** [comment]
We concluderen na divers feedback dat we Chloride meting in het veld niet opnemen.
