### ISSUE TITLE
Samenhang en afstemming andere standaarden (Aquo/ SIKB) / opbouw parameterlijst

### ISSUE THREAD

**Issue by KoosBoersma** [BROprogramma/GAR#54]
## Type issue
Publieke consultatie

## Waar
1.1.6 Objecttype Resultaat veldmetingen  (als eerste, maar ook van toepassing op alle andere)

## Samenvatting
Aquo maakt gebruik bij resultaten van metingen van een samenstelling lijst Parametersoort bestaande uit Typering.Code | Grootheid.Code | Parameter.Code | Eenheid.code | Hoedanigheid.code | Analysecompartiment.code

## Beschrijving
Het ontbreekt aan een flexibele opbouw van meetingen en zijn verschillende vormen/spec. Deze opmerking is voor meerdere items in het document van toepassing en is daarmee ook vooral een fundamenteel issue.  

## Oplossingsrichting
Gebruik de bestaande standaard methodes van Aquo/SIKB. Zowel qua inhoud als methodiek.

**Comment by AnnitaVijverberg** [comment]
Roeland Heuff, SIKB
## Type issue
Publieke consultatie

## Beschrijving
Bij SIKB wordt een PhysicalProperty opgebouwd uit delen:
- parameter
- hoedanigheid
- grootheid
In de SIKB parameterlijst staat een kolom 'Groep' (chemische stof, grootheid, object, ongedefinieerdLab, typering, typeringMarien)

**Comment by AnnitaVijverberg** [comment]
Binnen de Bro hebben we gekozen de parameters te standardiseren, daarmee wordt het minder flexibel. Vanwege uniformiteit hebben we de eenheid (muv de prefix) vastgelegd. Het gaat hier om grondwaterkwaliteit, de parameterlijst in de Bro is uitsluitend voor grondwater waardoor veel de variatie die SIKB biedt niet relevant is. De relevante grootheden zoals pH, temperatuur EGV etc hebben we wel meegenomen in de parmeterlijst waarin het  (SIKB) ID de sleutel is. De SIKB datamodellen zijn via het ID te mappen op de Bro.

**Comment by RLHuisman** [comment]
Voor de chemische parameters wordt dus altijd de grootheid Concentratie toegepast, dus vanuit SIKB mappen naar de BRO voor checmische parameters alleen doen voor Concentraties.

**Comment by AnnitaVijverberg** [comment]
> Voor de chemische parameters wordt dus altijd de grootheid Concentratie toegepast, dus vanuit SIKB mappen naar de BRO voor checmische parameters alleen doen voor Concentraties.

klopt
