### ISSUE TITLE
waardebepalingstechniek vs bepalingstechniek

### ISSUE THREAD

**Issue by KoosBoersma** [BROprogramma/GAR#55]
## Type issue
Publieke consultatie

## Waar
1.2.8. Codelijst details Bepalingstechniek

## Samenvatting
Binnen Aquo en SIKB heet dit WaardeBepalingsTechniek

## Beschrijving
De lijst met waardebepalingstechniek (aquo) en bepalingstechniek (BRO) heeft gelijke doel inhoud. 

## Oplossingsrichting
Zorg ervoor dat de verschillende lijsten onderling (tussen de standaarden) dezelfde verzamelnaam hanteren. Dus aanpassen Bepalingstechniek naar Waardebepalingstechniek. 
Hiermee wordt de mogelijkheid voor uitwisseling van gegevens onderling veel makkelijker en duidelijker gemaakt.

**Comment by AnnitaVijverberg** [comment]
provincies via Platform Meetnetbeheerders:
Waarom moet deze heel uitgebreide lijst worden opgenomen.  Is deze limitief? Voegt volgens mij niet zoveel toe en is foutgevoelig. Als een gebruiker daar informatie over wil hebben dan kan deze toch ook de analysecertificaten opvragen bij de bronhouder?

**Comment by KoosBoersma** [comment]
Annita, Ik volg je opmerking niet. De bepalingstechniek is binnen een nederlandse standaard Aquo reeds aanwezig, en namelijk met de naam waardebepalingstechniek. Deze lijst met methodes wordt gebruikt  door Waterschappen, SIKB en RWS. Mijn vraag is vooral waarop de BRO ervoor gekozen heeft aan een gelijk item een andere verzamelnaam toe te kennen. Volgens mij is het handig ook de standaarden onderling in lijn te brengen. Qua inhoud van de lijst is deze flexible

**Comment by AnnitaVijverberg** [comment]
Koos, de bovenstaande opmerking is er een van de provincies via Platform Meetnetbeheerders. Zij hebben hun opmerkingen niet rechtstreeks in Github gezet maar naar ons (BRO standaardisatie) gemaild. Wij zetten ze in Github. Omdat deze opmerking over hetzelfde onderwerp gaat, de (Waarde)bepalingstechniek, heb ik hem hierbij geplaatst.

**Comment by KoosBoersma** [comment]
Annita,

Misschien is het wel goed om even een afspraak te maken. Tav van mijn meer structureel punt. Bij wie moeten we dan zijn?

Gr, Koos.

**Comment by AnnitaVijverberg** [comment]
De naam bepalingstechniek is aangepast naar waardebepalingstechniek.
Het is een bewuste keuze dit op te nemen omdat de gebruikte techniek een duiding is van de gemeten waarde. De lijst is overgenomen van de SIKB/IHW codelijst en zal in de beheerfase geupdate worden indien nodig.
