### ISSUE TITLE
Afwijkende naam BRO Bepalingsprocedure versus Aquo Waardebepalingsmethode

### ISSUE THREAD

**Issue by KoosBoersma** [BROprogramma/GAR#56]
## Type issue
Publieke consultatie

## Waar
1.2.9. Codelijst details Bepalingsprocedure 

## Samenvatting
Afwijkende namen voor hetzelfde item

## Beschrijving
Verschillende namen voor hetzelfde item tussen de standaard BRO en AQUO

## Oplossingsrichting
Pas gelijke namen toe. Help qua uitwisseling en het onderling met elkaar verbinden van de standaarden. Deze check doen voor alle inderdelen.

**Comment by AnnitaVijverberg** [comment]
provincies via Platform Meetnetbeheerders:
Waarom moet deze heel uitgebreide lijst worden opgenomen.  Is deze limitief? Voegt volgens mij niet zoveel toe en is foutgevoelig. Als een gebruiker daar informatie over wil hebben dan kan deze toch ook de analysecertificaten opvragen bij de bronhouder?

**Comment by KoosBoersma** [comment]
Annita, Ik volg je opmerking niet. De bepalingsprocedure is binnen een nederlandse standaard Aquo reeds aanwezig, en namelijk met de naam Waardebepalingsmethode. Deze lijst met methodes wordt ook gebruikt door alle labaratoruims in nederland welke volgens de SIKB methode werken. Mijn vraag is vooral waarop de BROervoor gekozen heeft aan een gelijk item een andere verzamelnaam toe te kennen. Volgens mij is het handig ook de standaarden onderling in lijn te brengen. Qua inhoud van de lijst is deze flexible aangezien je een toepassingsgebied kunt opnemen.

**Comment by AnnitaVijverberg** [comment]
Roeland Heuff, SIKB
## Type issue
Publieke consultatie

## Beschrijving
Gebruikte veldnamen en namen van codelijsten zijn anders dan wat we binnen SIKB0101/AQUO/Metingen gewend zijn. Voor de herkenbaarheid het dit logisch zijn om dit gelijk te trekken. Zeker omdat de inhoud deels 1 op 1 is overgenomen.

**Comment by AnnitaVijverberg** [comment]
De naam Bepalingsprocedure is aangepast naar Waardebepalingsprocedure.
We hebben niet gekozen voor waardebepalingsmethode omdat binnen de BRO de term procedure steeds gebruikt wordt voor het aanduiden van normen en richtlijnen. Daar houden we hier voor de eenduidigheid binnen de BRO ook aan vast.
Ook andere codelijsten en attribuutnamen gecheckt en waar mogelijk aangepast.
Het is een bewuste keuze dit op te nemen omdat de gebruikte procedure een duiding is van de gemeten waarde. De lijst is overgenomen van de SIKB/IHW codelijst en zal in de beheerfase geupdate worden indien nodig.
