### ISSUE TITLE
Structuur en hierarchie in domein

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#6]
Het [domeinmodel GAR][1] is nog niet definitief. Over de structuur en hiërarchie (de 'kapstok') wordt nog nagedacht. Bijvoorbeeld: 

- Monster en deelmonsters. Deze krijgen mogelijk een plek in het model. Dit zijn onderdelen van het totale monster, genomen tijdens het veldonderzoek, waarvoor gelijke eisen tav conservering, transport en voorbewerking gelden. Daarom is dit wellicht een relevante groepering om terug te laten komen in het domeinmodel.
 - Analyse. Eén analysemethode + onderzoeksnorm kunnen horen bij meerdere parameters die onderzocht zijn binnen een deelmonster. 
- Parameter. Er zijn twee soorten parameters: fysische parameters en chemische parameters. Wellicht wordt dit onderscheid in het domeinmodel aangebracht. 
  - Fysische parameters, zoals temperatuur, elektrische geleidbaarheid en zuurgraad. Dit betreft eigenschappen van het monster als geheel. Ze geven niet direct informatie over de samenstelling van het monster, maar eerder een typering ervan.
  - Chemische parameters: dit betreft het gehalte (de concentratie) van een bepaald element of bepaalde stof in het grondwater. De chemische parameters zeggen daadwerkelijk iets over de samenstelling van het monster [‘de delen van het monster die geen water zijn’].

[1]: https://broprogramma.github.io/GAR/#domeinmodel-gmm

**Comment by AnnitaVijverberg** [comment]
Dit issue was een aandachtspunt voor standaardisatieteam. We hebben het inmiddels opgepakt:
- Monsters/deelmonsters buiten scope
- Analysemethode en normen, staat op backlog voor standaardisatieteam
- parameters zijn verwerkt in het model

**Comment by AnnitaVijverberg** [comment]
We sluiten dit issue zoals besproken in de sprintreview van 25 okt 2018
