### ISSUE TITLE
Kader 'in opdracht van bestuursorgaan'

### ISSUE THREAD

**Issue by RosaSjerps** [BROprogramma/GAR#72]
## Type issue
Publieke consultatie

## Waar
toelichting 1 grondwatermonitoring, pagina 41, alinea 4

## Samenvatting
De tekst mist voorbeelden

## Beschrijving
De omschrijving 'de grondwatermonitoring moet door of in opdracht van een bestuursorgaan, de bronhouder, worden uitgevoerd' mist voorbeelden. Zo vraagt de drinkwatersector zich af,  is grondwatermonitoring ten behoeve van de waterwinvergunning onderdeel van een in opdracht uitgevoerde grondwatermonitoring van een bestuursorgaan? 

## Oplossingsrichting
Geef concreet aan met voorbeelden wat wordt bedoeld met een in opdracht uitgevoerde grondwatermonitoring. Welke partijen zijn hierbij betrokken en op welke manier kan de opdracht worden verleend?

**Comment by AnnitaVijverberg** [comment]
"De grondwatermonitoring moet door of in opdracht van een bestuursorgaan, de bronhouder, worden uitgevoerd." is de letterlijke tekst uit Besluit basisregistratie ondergrond. 
Wel een zin opgenomen : "Het bestuursorgaan dat optreedt als bevoegd gezag kan het registreren van deze gegevens als voorwaarde opnemen in de beschikking van de betreffende vergunningsaanvragen." en verwezen naar het scopedocument.
