### ISSUE TITLE
Figuur 2

### ISSUE THREAD

**Issue by RosaSjerps** [BROprogramma/GAR#78]
## Type issue
Publieke consultatie

## Waar
figuur 2 op pagina 45

## Samenvatting
de figuur mist voldoende toelichting

## Beschrijving
Bij figuur 2 mist een beschrijving voor de activiteiten, doelstelling, afstemming bronhouder, opdrachtverlening. Het is onduidelijk waarom dit niet wordt beschreven. 
Hoe past een drinkwaterbedrijf dat volgens de winvergunning gegevens aan de bronhouder levert binnen deze figuur? Is een drinkwaterbedrijf in dit geval de opdrachtnemer? In dit geval, is het drinkwaterbedrijf verantwoordelijk voor de controle en beoordeling van de gegevens?

## Oplossingsrichting
Graag figuur 2 in zijn geheel beschrijven of reden geven waarom dit niet verder wordt toegelicht. Beschrijf het proces van bronhouder (opdrachtgever) en opdrachtnemer, welke partijen zijn hier betrokken? Kan dit ook een drinkwaterbedrijf zijn?

**Comment by AnnitaVijverberg** [comment]
In de tekst boven de figuur een nadere toelichting gegeven op de onderdelen die niet worden besproken onder de figuur en in het vervolg van de catalogus.
Drinkwaterbedrijven zijn een voorbeeld van private organisaties die vanuit vergunningsplicht het grondwater monitoren op grondwaterkwaliteit, in opdracht van bevoegd gezag. 
Op dit moment is het bevoegd gezag de bronhouder en er verantwoordelijk voor dat gegevens van drinkwaterbedrijven (verkregen vanuit een vergunningsplicht) in de BRO komen. Er wordt nog besproken of dit ook anders opgelost zal gaan worden (in de vorm van gedelegeerd bronhouder of met de rol van producent bijv.).  Dat is op dit moment nog niet duidelijk en kunnen we daarom in de catalogus niets over zeggen.
