### ISSUE TITLE
Relatie GAR - meetpunt

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#8]
Er is een relatie tussen het grondwatersamenstellingsonderzoek en een meetpunt (de abstractie van de grondwaterput of bron waar het onderzoek is gedaan) in een grondwatermonitoringsnet, een ander BRO registratieobject. Hoe deze relatie precies wordt gemodelleerd en gerealiseerd moet nog worden afgestemd. De relatie heeft ook een temporele component; bij meetnet hoort een meetprogramma en een frequentie. Meetpunten krijgen een volgnummer in een meetnet, dat eventueel kan worden gebruikt als ID waarnaar gerefereerd kan worden.

**Comment by lvdbrink** [comment]
Marielle van Vliet (TNO): 
> Issue is me niet duidelijk. Wel dat dit belangrijk is voor de koppeling tussen putfilters en analyses. Volgens mij moet hier nog goed over gediscussieerd worden.

**Comment by lvdbrink** [comment]
Inderdaad is dit nog een open punt voor discussie.

**Comment by rbv305** [comment]
Is het een idee om het meetprogramma te verwerken in de kaders voor monitoring ? Een meting wordt tenslotte gedaan in het kader van een monitoringsprogramma (kaderrichtlijn water 2018 bv).

**Comment by AnnitaVijverberg** [comment]
Nu ook het RO Grondwatermonitoringnet is beschreven is de relatie tussen GAR (grondwatersamenstellingsonderzoek), GMW (grondwatermonitoringput) en GMN (grondwatermonitoringnet) uitgekristalliseerd.
