### ISSUE TITLE
Opdrachtnemers

### ISSUE THREAD

**Issue by RosaSjerps** [BROprogramma/GAR#80]
## Type issue
Publieke consultatie

## Waar
Paragraaf 4.1 pagina 47. 2e alinea 1e zin.

## Samenvatting
De tekst is hier onduidelijk.

## Beschrijving
In deze formulering is het onduidelijk wie het behoren tot opdrachtnemers. 

## Oplossingsrichting
Graag omschrijven wie opdrachtnemers kunnen zijn. Zijn dat enkel adviesbureaus of ook drinkwaterbedrijven?

**Comment by AnnitaVijverberg** [comment]
Dit staat verder uitgelegd in hst1 van de toelichting en nog uitgebreider in het Scopedocument grondwatersamenstellingsonderzoek GAR. Daarnaar is nu in hst1 ook verwezen. Zie ook issue #72
