### ISSUE TITLE
meettechnieken, normen en parameters met/zonder accreditatie

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GAR#9]
Bij parameters die onder accreditatie vallen hoeft in de BRO geen informatie te worden opgenomen over normen, analysemethoden en procedures op parameterniveau omdat deze via de accreditatie te achterhalen is. 

Er zijn echter ook parameters die niet onder accreditatie vallen. Wellicht moeten we dus in de BRO wel bij deze parameters informatie vastleggen over normen, analysemethoden en procedures op parameter niveau.

**Comment by AnnitaVijverberg** [comment]
Feedback Provincies over accreditatie van individuele stoffen. “Vaak hebben we geen idee van hoe het in het verleden is uitgevoerd, voor de toekomstige metingen hebben we de uitvoeringslijsten van de labs, ik zou hier eigenlijk geen punt van willen maken. We doen bij aanlevering van de gegevens een opgave van de door het lab gebruikte technieken.”

**Comment by AnnitaVijverberg** [comment]
Kijken we naar als we aan lab-parameters werken voor IMBRO/A.

**Comment by JvVelthuijsen** [comment]
De meeste 'bekende' parameters vallen onder accreditatie. Maar een groot aantal nieuwe stoffen, geneesmiddelen en enkele bestrijdingsmiddelen (nog) niet.

**Comment by rbv305** [comment]
Als de informatie over de normen, analyses en procedures eenvoudig geleverd kunnen worden door de labs zie ik geen bezwaar om ze op te nemen.

**Comment by AnnitaVijverberg** [comment]
Uit het gesprek met Janco van Gelderen: Labs hebben een accreditatie voor bepaalde stoffen, vaak niet voor alle stoffen. Stoffen waar ze geen accreditatie voor hebben worden vaak middels een 'eigen procedure' gemeten. Een meting van een stof waar een lab een accreditatie voor heeft, kan toch zonder Q zijn. Dit gebeurt als bijvoorbeeld de conserveringstermijn is overschreden.

**Comment by JancovanGelderen** [comment]
Provincies kunnen bij alle metingen een lijst overhandigen met de door het lab toegepaste analyse methoden, vraag is of die direct aan de metingen wordt gekoppeld of dat die aan de meetronde als geheel, via monitoring net wordt gekoppeld.

**Comment by AnnitaVijverberg** [comment]
Input HWL:
        Voor een stof zijn soms meer technieken mogelijk.
        Voor een techniek kunnen meer normen/voorschriften gelden.
        Een norm hoort altijd bij 1 techniek.

Het heeft voor de gebruiker waarde te weten welke meettechniek is gebruikt. Het is bepalend voor de uitkomst, cruciaal. Met de meettechniek krijg je informatie over de nauwkeurigheid, maar ook zegt de techniek bijv filtratie over bepaald grootte filter gefiltreerd is (of helemaal geen filtratie), dat beïnvloed sterk de uitkomst van de meeting
 
Keuze door het lab voor welke norm (techniek) is gebruikt, is afhankelijk van toepassingsgebied. Als je lage gehaltes verwacht, wil je met een nauwkeurige techniek meten. Als conform een norm gemeten is de uitslag betrouwbaar. Zonder norm weet je eigenlijk niet wat de betrouwbaarheid is.

**Comment by AnnitaVijverberg** [comment]
De keuze om technieken en normen op te nemen ipv te verwijzen naar de website van de Raad van Accreditatie (www.rva.nl) is gemaakt op:
- HWL geeft aan dat begrippen conform norm X en gelijkwaardig aan norm X en de methode in 2019 uit de scope gehaald worden. Dit i.v.m. concurrentie bij aanbestedingen. Dat betekent dat van de website dan niet meer (goed) te achterhalen is welke techniek een lab gebruikt voor het meten van een stof en volgens welke norm of voorschrift gemeten wordt..
- Op dit moment is op de website www.rva.nl alleen de huidige scope te vinden. De historie is er niet te vinden. Over 5 jaar weet een gebruiker van de BRO daarom niet meer met welke methode en procedure een lab een parameter heeft gemeten.

**Comment by rbv305** [comment]
lijkt me niet wenselijk om niet meer te kunnen achterhalen welke techniek er in het verleden is gebruikt. Voor trendanalyse lijkt mij dit relevante informatie.

**Comment by AnnitaVijverberg** [comment]
We hebben overwogen of we naast de bepalingstechniek (de analysetechniek die gebruikt is bij het bepalen van het gehalte van stoffen) en de bepalingsprocedure (de norm of het voorschrift dat beschrijft hoe het onderzoek is uitgevoerd) ook opnemen of een lab voor een analyse geaccrediteerd is.
Wanneer een lab een accreditatie heeft,  wordt bij de bepalingsprocedure, een NEN-norm (e.d.) opgegeven. In het andere geval wordt bij bepalingsprocedure gekozen voor een 'Niet genormaliseerde automatische waardebepaling toegepast'. Wellicht dat in enkele gevallen dit uitgangspunt niet klopt. We gaan ervan uit dat in de meeste gevallen dit uitgangspunt klopt en nemen daarom in de BRO niet nog meer detail op in de vorm van wel/niet geaccrediteerd.
